// Generated by scripts/build-map-footprints.ts; edit via scripts/map-collision-tool.ts.
// Grounded solids (building bodies, wells, stalls, ponds, rock piles) for the painted
// /maps/<id>.webp locations, in 960×640 world units. Perimeter walls, gates and paths
// stay open by design; world-navigation.test.ts proves every marker stays reachable.
import type { WorldFootprint } from "./world-navigation";

export const PAINTED_MAP_FOOTPRINTS: Readonly<Record<string, readonly WorldFootprint[]>> = {
  city_suzhou: [
    { kind: "rect", left: 162, top: 178, right: 402, bottom: 262 },
    { kind: "rect", left: 100, top: 200, right: 150, bottom: 240 },
    { kind: "ellipse", x: 480, y: 312, radiusX: 30, radiusY: 22 },
    { kind: "rect", left: 178, top: 340, right: 238, bottom: 384 },
    { kind: "rect", left: 570, top: 110, right: 770, bottom: 246 },
    { kind: "rect", left: 642, top: 312, right: 835, bottom: 394 },
    { kind: "rect", left: 262, top: 405, right: 693, bottom: 470 },
  ],
};
