import type {
  ArtisanDef,
  ArtisanEquipOffer,
  ArtisanRecipeOffer,
  ItemCategory,
} from "../types";
import { RECIPES } from "./recipes";

// ─── Artisan registry ─────────────────────────────────────────────────
//
// Player-facing crafting NPCs. Each artisan exposes:
//   1. recipes for sale (player buys to add to learnedRecipeIds)
//   2. a craft menu using learned recipes that match this profession
//   3. a small sale inventory + sell-back at sellMultiplier
//
// Cities host all 6 craft professions (forge / alchemy / tailoring /
// chef / jewelry / accessory) — the city roster is auto-generated by
// `buildCityArtisan` so adding a new city = one line below.
//
// Villages and sects host a single artisan each, hand-curated for lore
// fit (sect_huashan = swordsmith, etc.).
//
// Recipe assembly: each artisan's `recipes` array lists *specialty*
// offerings. Basic recipes (RecipeDef.basic === true) of the same
// profession are folded in by `recipesOfferedBy()` so a village shop
// always teaches at least the staples.

// ─── Profession metadata ─────────────────────────────────────────────
const PROF_LABEL: Record<CraftProfession, string> = {
  forge:     "ช่างตีเหล็ก",
  alchemy:   "ช่างปรุงยา",
  tailoring: "ช่างตัดเย็บ",
  chef:      "พ่อครัว",
  jewelry:   "ช่างเครื่องประดับ",
  accessory: "ช่างเครื่องสาน",
};

const PROF_ICON: Record<CraftProfession, string> = {
  forge:     "🔨",
  alchemy:   "🧪",
  tailoring: "🧵",
  chef:      "🍳",
  jewelry:   "💍",
  accessory: "🪭",
};

// Sale inventory by profession — items the artisan stocks for purchase
// (typically a mix of crafted goods + basic profession-relevant
// materials so the player can buy ingredients on the same trip).
const PROF_INVENTORY: Record<CraftProfession, readonly string[]> = {
  forge:     ["iron_ingot", "iron_blade", "iron_sword"],
  alchemy:   ["potion", "potion_mid", "herb", "ginseng"],
  tailoring: ["thread", "cloth_robe", "leather_robe"],
  chef:      ["rice_dish", "spicy_stew", "moon_cake", "cooked_meat"],
  jewelry:   ["silver_ring", "gold_ring", "silver_ore"],
  accessory: ["thread", "cloth_robe"], // accessory items added by Phase A4
};

// Categories each artisan accepts for player-sells. Specialised — a
// blacksmith only buys metal/material; an alchemist takes herb/venom.
const PROF_ACCEPTS: Record<CraftProfession, readonly ItemCategory[]> = {
  forge:     ["material"],
  alchemy:   ["herb", "venom", "potion"],
  tailoring: ["material"],
  chef:      ["food", "herb", "material"],
  jewelry:   ["material", "valuable"],
  accessory: ["material", "valuable"],
};

// ─── Equipment offers ────────────────────────────────────────────────
// Tier 0-1 equipment is sold by every artisan of the matching
// profession (the "basic" roster). City-specific specialty pieces are
// listed in CITY_EQUIPMENT_SPECIALTIES below — those override / append
// per-artisan.
//
// Equipment id ↔ profession mapping is held in PROF_BASIC_EQUIPMENT;
// prices come from EQUIPMENT_PRICE. Authors extend the system by:
//   - adding a new equipment id to lib/game/data/equipment.ts
//   - registering the id under the right profession below + giving it
//     a base price
//   - (optional) appending a row to CITY_EQUIPMENT_SPECIALTIES to
//     restrict it to a specific city's artisan with its own price

const PROF_BASIC_EQUIPMENT: Record<CraftProfession, readonly string[]> = {
  forge: [
    // tier 0 weapons + iron armor
    "eq_t0_w_fist", "eq_t0_w_long", "eq_t0_w_sword", "eq_t0_w_blade",
    "eq_t0_w_short", "eq_t0_w_hidden",
    "eq_t0_a_iron", "eq_t0_h_iron", "eq_t0_b_iron", "eq_t0_br_iron",
    // tier 1 weapons + iron armor
    "eq_t1_w_fist", "eq_t1_w_long", "eq_t1_w_sword", "eq_t1_w_blade",
    "eq_t1_w_short", "eq_t1_w_hidden",
    "eq_t1_a_iron", "eq_t1_h_iron", "eq_t1_b_iron", "eq_t1_br_iron",
  ],
  tailoring: [
    "eq_t0_a_cloth", "eq_t0_h_cloth", "eq_t0_b_cloth", "eq_t0_br_cloth",
    "eq_t1_a_leather", "eq_t1_h_leather", "eq_t1_b_leather", "eq_t1_br_leather",
  ],
  jewelry:   ["eq_t0_r_copper", "eq_t1_r_silver"],
  accessory: ["eq_t0_c_cloth",  "eq_t1_c_wood"],
  alchemy:   [],
  chef:      [],
};

// Base price per equipment id. Used for the basic roster fan-out;
// specialty offers override via CITY_EQUIPMENT_SPECIALTIES.
const EQUIPMENT_PRICE: Record<string, number> = {
  // tier 0
  eq_t0_w_fist:   60,
  eq_t0_w_long:   70,
  eq_t0_w_sword:  65,
  eq_t0_w_blade:  75,
  eq_t0_w_short:  55,
  eq_t0_w_hidden: 50,
  eq_t0_a_cloth:  80,
  eq_t0_h_cloth:  40,
  eq_t0_b_cloth:  35,
  eq_t0_br_cloth: 30,
  eq_t0_a_iron:  140,
  eq_t0_h_iron:   70,
  eq_t0_b_iron:   60,
  eq_t0_br_iron:  55,
  eq_t0_r_copper: 90,
  eq_t0_c_cloth: 100,
  // tier 1
  eq_t1_w_fist:   240,
  eq_t1_w_long:   280,
  eq_t1_w_sword:  260,
  eq_t1_w_blade:  300,
  eq_t1_w_short:  220,
  eq_t1_w_hidden: 220,
  eq_t1_a_leather:  340,
  eq_t1_h_leather:  170,
  eq_t1_b_leather:  150,
  eq_t1_br_leather: 130,
  eq_t1_a_iron:     480,
  eq_t1_h_iron:     220,
  eq_t1_b_iron:     200,
  eq_t1_br_iron:    180,
  eq_t1_r_silver:   320,
  eq_t1_c_wood:     280,
};

// City × profession × specialty equipment. Mirrors CITY_SPECIALTIES for
// recipes — append a row to give a city's artisan a unique stock entry.
const CITY_EQUIPMENT_SPECIALTIES: readonly {
  city: string;
  prof: CraftProfession;
  equipId: string;
  price: number;
}[] = [
  // Xixia frontier forge — heavy steel saber.
  { city: "city_xixia",    prof: "forge",     equipId: "eq_xixia_w_blade",   price: 720 },
  // Yangzhou river forge — curved evasive saber.
  { city: "city_yangzhou", prof: "forge",     equipId: "eq_yangzhou_w_blade", price: 680 },
  // Suzhou silk tailor — premium silk armor.
  { city: "city_suzhou",   prof: "tailoring", equipId: "eq_suzhou_a_silk",   price: 850 },
  // Jinling jeweler — court-grade jade ring.
  { city: "city_jinling",  prof: "jewelry",   equipId: "eq_jinling_r_jade",  price: 900 },
  // Dali herbalist accessory — regen charm.
  { city: "city_dali",     prof: "accessory", equipId: "eq_dali_c_herb",     price: 520 },
  // Changan imperial forge — military bracers.
  { city: "city_changan",  prof: "forge",     equipId: "eq_changan_br_iron", price: 460 },
  // Capital court accessory — imperial seal charm.
  { city: "city_capital",  prof: "accessory", equipId: "eq_capital_c_seal",  price: 780 },
];

function specialtyEquipFor(
  city: string,
  prof: CraftProfession,
): readonly ArtisanEquipOffer[] {
  return CITY_EQUIPMENT_SPECIALTIES
    .filter((s) => s.city === city && s.prof === prof)
    .map(({ equipId, price }) => ({ equipId, price }));
}

// ─── City artisan auto-generator ─────────────────────────────────────
// Cities that host the full 6-profession roster. Adding a new city =
// one line here; the helper builds all 6 ArtisanDefs.
const CITIES_WITH_FULL_ROSTER: readonly { id: string; name: string }[] = [
  { id: "city_capital",  name: "นครหลวง" },
  { id: "city_xixia",    name: "ซีเซี่ย" },
  { id: "city_dali",     name: "ต้าหลี่" },
  { id: "city_yangzhou", name: "หยางโจว" },
  { id: "city_suzhou",   name: "ซูโจว" },
  { id: "city_jinling",  name: "จินหลิง" },
  { id: "city_changan",  name: "ฉางอัน" },
];

const ALL_PROFESSIONS: readonly CraftProfession[] = [
  "forge",
  "alchemy",
  "tailoring",
  "chef",
  "jewelry",
  "accessory",
];

// City-specific specialty recipes. When a city wants to host a unique
// recipe at a specific artisan, append { city, prof, recipeId, price }
// here. The helper folds these into the matching artisan automatically;
// missing entries simply mean that artisan only sells basic recipes.
//
// Authors can keep adding rows here — the registry stays compact.
const CITY_SPECIALTIES: readonly {
  city: string;
  prof: CraftProfession;
  recipeId: string;
  price: number;
}[] = [
  // Xixia — frontier blacksmith city. Premium steel.
  { city: "city_xixia", prof: "forge", recipeId: "forge_steel_sword", price: 600 },
  // Suzhou — silk capital. Top-tier robe.
  { city: "city_suzhou", prof: "tailoring", recipeId: "tailor_silk", price: 700 },
  // Dali — alchemy + herbalist hub. Heavy potions.
  { city: "city_dali", prof: "alchemy", recipeId: "alchemy_potion_big", price: 800 },
  { city: "city_dali", prof: "alchemy", recipeId: "alchemy_poison", price: 500 },
  // Capital — court chef.
  { city: "city_capital", prof: "chef", recipeId: "chef_moon_cake", price: 250 },
  // Jinling — jade jeweller.
  { city: "city_jinling", prof: "jewelry", recipeId: "jewel_jade_amulet", price: 900 },
  { city: "city_jinling", prof: "jewelry", recipeId: "jewel_gold_ring", price: 400 },
  // Yangzhou — accessory specialty (silk fan, jade pendant).
  { city: "city_yangzhou", prof: "accessory", recipeId: "accessory_silk_fan", price: 350 },
  // Changan — accessory specialty (warrior's belt).
  { city: "city_changan", prof: "accessory", recipeId: "accessory_warrior_belt", price: 450 },
];

function specialtiesFor(
  city: string,
  prof: CraftProfession,
): readonly ArtisanRecipeOffer[] {
  return CITY_SPECIALTIES
    .filter((s) => s.city === city && s.prof === prof)
    .map(({ recipeId, price }) => ({ recipeId, price }));
}

function buildCityArtisan(
  cityId: string,
  cityName: string,
  prof: CraftProfession,
): ArtisanDef {
  const icon = PROF_ICON[prof];
  const role = PROF_LABEL[prof];
  return {
    id: `artisan_${cityId}_${prof}`,
    locationId: cityId,
    profession: prof,
    label: `${icon} ร้าน${role}แห่ง${cityName}`,
    npcName: `${role}แห่ง${cityName}`,
    description: `${role}ประจำเมือง${cityName} รับซื้อของ ขายวัตถุดิบ และสอนสูตรเฉพาะของท้องถิ่น`,
    recipes: specialtiesFor(cityId, prof),
    equipment: specialtyEquipFor(cityId, prof),
    inventory: PROF_INVENTORY[prof],
    acceptsCategories: PROF_ACCEPTS[prof],
    sellMultiplier: 0.4,
  };
}

const CITY_ARTISANS: readonly ArtisanDef[] = CITIES_WITH_FULL_ROSTER.flatMap(
  (c) => ALL_PROFESSIONS.map((p) => buildCityArtisan(c.id, c.name, p)),
);

// ─── Village + sect artisans (single-profession lore picks) ──────────
//
// `equipment: []` here means "only the profession's basic roster" — the
// helper `equipmentOfferedBy()` auto-folds those in. Hand-picked
// specialty equipment (e.g., the sect huashan-forge "school-pattern
// sword") goes into the array.
const SINGLE_PROFESSION_ARTISANS: readonly ArtisanDef[] = [
  // ── Villages — one craft each, matching the village's flavour ────
  {
    id: "artisan_village_huashan_forge",
    locationId: "village_huashan",
    profession: "forge",
    label: "🔨 ร้านตีเหล็กหมู่บ้านหัวซาน",
    npcName: "ช่างเหล็กถัง",
    description: "ช่างเหล็กรุ่นเก่าตีดาบให้ลูกศิษย์หัวซานมานานหลายชั่วคน",
    recipes: [],
    equipment: [],
    inventory: ["iron_ingot", "iron_blade"],
    acceptsCategories: ["material"],
    sellMultiplier: 0.35,
  },
  {
    id: "artisan_village_meihua_chef",
    locationId: "village_meihua",
    profession: "chef",
    label: "🍳 โรงครัวดอกเหมย",
    npcName: "แม่ครัวเสี่ยวหง",
    description: "ทำอาหารดอกเหมยสูตรประจำหมู่บ้าน รสหวานหอมตามฤดูกาล",
    recipes: [],
    equipment: [],
    inventory: ["rice_dish", "moon_cake"],
    acceptsCategories: ["food", "herb"],
    sellMultiplier: 0.35,
  },
  {
    id: "artisan_village_qigu_alchemy",
    locationId: "village_qigu",
    profession: "alchemy",
    label: "🧪 ร้านปรุงยาชีกู่",
    npcName: "หมอเฒ่าฉี",
    description: "ปรุงยาเลือดในบ้านไม้เก่าหน้าหมู่บ้าน รับวัตถุดิบป่าทุกชนิด",
    recipes: [],
    equipment: [],
    inventory: ["potion", "herb"],
    acceptsCategories: ["herb", "venom"],
    sellMultiplier: 0.35,
  },
  {
    id: "artisan_village_wuxia_tailor",
    locationId: "village_wuxia",
    profession: "tailoring",
    label: "🧵 ร้านตัดเย็บอวู่เซี่ย",
    npcName: "ช่างเย็บลีหญิง",
    description: "ช่างตัดเสื้อหนังที่รู้จักกันทั้งปากแม่น้ำ ไม่ขายผ้าไหม",
    recipes: [],
    equipment: [],
    inventory: ["thread", "leather_robe"],
    acceptsCategories: ["material"],
    sellMultiplier: 0.35,
  },

  // ── Sects — one craft each. Sects with thematic crafting fit only.
  {
    id: "artisan_sect_huashan_forge",
    locationId: "sect_huashan",
    profession: "forge",
    label: "🔨 ลานตีดาบสำนักหัวซาน",
    npcName: "ผู้พิทักษ์ตีเหล็กหวาง",
    description: "ลานตีดาบในสำนักหัวซาน ตีกระบี่ตามแบบฉบับสำนัก",
    recipes: [
      // Forge specialty for the sect's swordsmith identity
      { recipeId: "forge_iron_sword", price: 220 },
    ],
    // Sect specialty: the school-pattern iron sword sells here too.
    equipment: [{ equipId: "eq_t1_w_sword", price: 280 }],
    inventory: ["iron_ingot", "iron_blade", "iron_sword"],
    acceptsCategories: ["material"],
    sellMultiplier: 0.35,
  },
  {
    id: "artisan_sect_emei_alchemy",
    locationId: "sect_emei",
    profession: "alchemy",
    label: "🧪 ห้องยาง้อไบ๊",
    npcName: "อาจารย์เภสัชชิงเหมย",
    description: "ห้องยาประจำสำนักง้อไบ๊ ปรุงยารักษาและยาต้านพิษให้ลูกศิษย์",
    recipes: [
      { recipeId: "alchemy_potion_mid", price: 280 },
    ],
    equipment: [],
    inventory: ["potion", "potion_mid", "herb", "ginseng"],
    acceptsCategories: ["herb", "venom"],
    sellMultiplier: 0.35,
  },
  {
    id: "artisan_sect_wudu_alchemy",
    locationId: "sect_wudu",
    profession: "alchemy",
    label: "🧪 หอเบญจพิษ",
    npcName: "ผู้อาวุโสปรุงพิษเหมียว",
    description: "หอปรุงพิษของพรรคเบญจพิษ — เฉพาะผู้กล้าที่จิตใจไม่หวั่นไหว",
    recipes: [
      { recipeId: "alchemy_poison", price: 600 },
    ],
    equipment: [],
    inventory: ["poison_vial"],
    acceptsCategories: ["venom", "herb"],
    sellMultiplier: 0.35,
  },
];

// ─── Public registry ──────────────────────────────────────────────────
export const ARTISANS: readonly ArtisanDef[] = [
  ...CITY_ARTISANS,
  ...SINGLE_PROFESSION_ARTISANS,
];

const BY_LOCATION = new Map<string, ArtisanDef[]>();
for (const a of ARTISANS) {
  const list = BY_LOCATION.get(a.locationId);
  if (list) list.push(a);
  else BY_LOCATION.set(a.locationId, [a]);
}

export function getArtisansAt(locationId: string): readonly ArtisanDef[] {
  return BY_LOCATION.get(locationId) ?? [];
}

const BY_ID = new Map<string, ArtisanDef>(ARTISANS.map((a) => [a.id, a]));

export function getArtisan(id: string | null | undefined): ArtisanDef | null {
  if (!id) return null;
  return BY_ID.get(id) ?? null;
}

// ─── Recipe assembly helper ──────────────────────────────────────────
//
// Returns the full recipe list this artisan offers, with prices:
//   - basic recipes for the matching profession (auto-filled from
//     RECIPES.filter(r => r.basic && r.skill === profession))
//   - the artisan's specialty recipes (with their per-artisan prices)
//
// Basic recipes get a default price (PRICE_BASIC) — they're cheap because
// every shop of the same profession sells them. Specialty prices are
// hand-set per artisan in the `recipes` array above.

const PRICE_BASIC = 80;

export function recipesOfferedBy(
  artisan: ArtisanDef,
): readonly ArtisanRecipeOffer[] {
  const out: ArtisanRecipeOffer[] = [];
  const seen = new Set<string>();
  // Specialty first so a hand-set price wins over the basic default.
  for (const offer of artisan.recipes) {
    if (seen.has(offer.recipeId)) continue;
    seen.add(offer.recipeId);
    out.push(offer);
  }
  for (const r of RECIPES) {
    if (!r.basic) continue;
    if (r.skill !== artisan.profession) continue;
    if (seen.has(r.id)) continue;
    seen.add(r.id);
    out.push({ recipeId: r.id, price: PRICE_BASIC });
  }
  return out;
}

// Mirror of recipesOfferedBy for equipment — folds the artisan's
// specialty equipment offers + the basic roster for their profession
// (with prices from EQUIPMENT_PRICE). Specialty rows can override the
// basic price by listing the same equipId; first-write-wins, so
// specialty appears before basic in the loop.
export function equipmentOfferedBy(
  artisan: ArtisanDef,
): readonly ArtisanEquipOffer[] {
  const out: ArtisanEquipOffer[] = [];
  const seen = new Set<string>();
  for (const offer of artisan.equipment) {
    if (seen.has(offer.equipId)) continue;
    seen.add(offer.equipId);
    out.push(offer);
  }
  const basics = PROF_BASIC_EQUIPMENT[artisan.profession as CraftProfession];
  if (basics) {
    for (const equipId of basics) {
      if (seen.has(equipId)) continue;
      const price = EQUIPMENT_PRICE[equipId];
      if (typeof price !== "number") continue;
      seen.add(equipId);
      out.push({ equipId, price });
    }
  }
  return out;
}

// Internal type — narrows LifeSkill to the 6 craft professions used by
// artisans. Keeps `accessory` etc. discoverable to the type system.
type CraftProfession =
  | "forge"
  | "alchemy"
  | "tailoring"
  | "chef"
  | "jewelry"
  | "accessory";
