/**
 * Process painted composed-map art into game assets.
 *
 *   bun scripts/build-composed-assets.ts --from <dir> [--measure]
 *
 * <dir>/<asset>.png   one isometric object on a flat white background (ids in lib/world/data/composed/assets.ts)
 * <dir>/g_<material>.png  a square top-down ground texture (paving, plaza, dirt, grass, water, cobble)
 *
 * Objects are cut out of their background, trimmed and resized to
 * COMPOSED_PX_PER_UNIT pixels per world unit of their width →
 * public/maps/composed/<asset>.webp; their pixel sizes go to
 * lib/world/data/composed/asset-pixels.ts. Ground textures are made seamless
 * (blended with a half-wrapped copy of themselves so every edge continues the
 * opposite one) → public/maps/composed/ground/<material>.webp; the game turns
 * them onto the isometric grid. The painted sources are not kept in the repo.
 *
 * --measure only prints, for each object, where its lowest point sits across
 * the trimmed art: the footprint's bottom corner lies at a / (a + b) of the
 * width for a footprint of a × b tiles, which is how `tiles` are chosen.
 */
import sharp from "sharp";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { cutOut } from "./art-cutout";
import { COMPOSED_ASSETS, COMPOSED_PX_PER_UNIT, assetWidth } from "../lib/world/data/composed/assets";

const from = process.argv[process.argv.indexOf("--from") + 1];
if (!from || !existsSync(from)) throw new Error("usage: bun scripts/build-composed-assets.ts --from <dir> [--measure]");
const measure = process.argv.includes("--measure");
const OUT = "public/maps/composed";
mkdirSync(`${OUT}/ground`, { recursive: true });

const PIXELS_FILE = "lib/world/data/composed/asset-pixels.ts";
const pixels: Record<string, [number, number]> = {};
for (const m of readFileSync(PIXELS_FILE, "utf8").matchAll(/"([^"]+)": \[(\d+), (\d+)\]/g)) pixels[m[1]] = [Number(m[2]), Number(m[3])];

let objects = 0;
for (const [id, def] of Object.entries(COMPOSED_ASSETS)) {
  const source = `${from}/${id}.png`;
  if (!existsSync(source)) continue;
  // Strict pockets: plaster walls and paper lanterns have flat near-white areas.
  const cut = await cutOut(source, { pocketTolerance: 4, pocketMin: 600 });
  const trimmed = await sharp(cut).trim({ threshold: 8 }).toBuffer();
  if (measure) {
    const { data, info } = await sharp(trimmed).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
    const solid = (x: number, y: number) => data[(y * info.width + x) * 4 + 3] > 128;
    let lowest = -1;
    for (let y = info.height - 1; y >= 0 && lowest < 0; y--) for (let x = 0; x < info.width; x++) if (solid(x, y)) { lowest = y; break; }
    // The bottom corner: the middle of what is solid in the lowest 1.5 % of rows.
    const band = Math.max(2, Math.round(info.height * 0.015));
    const xs: number[] = [];
    for (let y = lowest - band; y <= lowest; y++) for (let x = 0; x < info.width; x++) if (solid(x, y)) xs.push(x);
    xs.sort((a, b) => a - b);
    const corner = xs[Math.floor(xs.length / 2)] / info.width;
    const [a, b] = def.tiles;
    console.log(`${id.padEnd(16)} ${info.width}×${info.height}  corner ${corner.toFixed(2)} (tiles ${a}×${b} → ${(a / (a + b)).toFixed(2)})`);
    continue;
  }
  const width = Math.round(assetWidth(def) * COMPOSED_PX_PER_UNIT);
  const out = await sharp(trimmed).resize({ width, kernel: "lanczos3" }).webp({ quality: 88, alphaQuality: 100 }).toBuffer();
  const meta = await sharp(out).metadata();
  writeFileSync(`${OUT}/${id}.webp`, out);
  pixels[id] = [meta.width!, meta.height!];
  objects++;
}
if (measure) process.exit(0);
for (const id of Object.keys(pixels)) if (!COMPOSED_ASSETS[id]) delete pixels[id];
writeFileSync(PIXELS_FILE, `// Generated by scripts/build-composed-assets.ts — processed image sizes (px) of public/maps/composed/<id>.webp.
export const COMPOSED_ASSET_PIXELS: Record<string, readonly [number, number]> = {
${Object.keys(pixels).sort().map((id) => `  "${id}": [${pixels[id][0]}, ${pixels[id][1]}],`).join("\n")}
};
`);

let grounds = 0;
const TILE = 512;
for (const material of ["paving", "plaza", "dirt", "grass", "water", "cobble"]) {
  const source = `${from}/g_${material}.png`;
  if (!existsSync(source)) continue;
  const { data } = await sharp(source).resize(TILE, TILE, { fit: "cover" }).removeAlpha().raw().toBuffer({ resolveWithObject: true });
  const out = Buffer.alloc(TILE * TILE * 3);
  // Weight of the original: 1 in the middle, easing to 0 at the edges, where the
  // half-wrapped copy (whose edges are the original's middle) takes over.
  const ramp = (t: number) => { const d = Math.min(t, TILE - 1 - t) / (TILE / 4); const k = Math.min(1, d); return k * k * (3 - 2 * k); };
  for (let y = 0; y < TILE; y++) for (let x = 0; x < TILE; x++) {
    const m = ramp(x) * ramp(y);
    const a = (y * TILE + x) * 3, b = (((y + TILE / 2) % TILE) * TILE + (x + TILE / 2) % TILE) * 3;
    for (let c = 0; c < 3; c++) out[a + c] = Math.round(data[a + c] * m + data[b + c] * (1 - m));
  }
  await sharp(out, { raw: { width: TILE, height: TILE, channels: 3 } }).webp({ quality: 86 }).toFile(`${OUT}/ground/${material}.webp`);
  grounds++;
}
console.log(`processed ${objects} objects and ${grounds} ground textures into ${OUT}/`);
