/**
 * Merge per-map footprint JSON (from map-collision-tool authoring) into
 * lib/stage/world-footprints-data.ts. Run: bun scripts/build-map-footprints.ts <dir>
 * Each <dir>/<locationId>.json is a WorldFootprint[]; values are rounded to integers.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import type { WorldFootprint } from "../lib/stage/world-navigation";

const dir = process.argv[2];
if (!dir) throw new Error("usage: bun scripts/build-map-footprints.ts <dir>");
/** Painted maps use rectangles and ellipses only. */
type PaintedFootprint = Exclude<WorldFootprint, { kind: "poly" }>;
const round = (f: PaintedFootprint): PaintedFootprint => f.kind === "rect"
  ? { kind: "rect", left: Math.round(f.left), top: Math.round(f.top), right: Math.round(f.right), bottom: Math.round(f.bottom) }
  : { kind: "ellipse", x: Math.round(f.x), y: Math.round(f.y), radiusX: Math.round(f.radiusX), radiusY: Math.round(f.radiusY) };
const entries = readdirSync(dir).filter((f) => f.endsWith(".json")).sort().map((file) => {
  const shapes = (JSON.parse(readFileSync(`${dir}/${file}`, "utf8")) as PaintedFootprint[]).map(round);
  for (const s of shapes) if (s.kind === "rect" ? !(s.right > s.left && s.bottom > s.top) : !(s.radiusX > 0 && s.radiusY > 0)) throw new Error(`${file}: degenerate shape`);
  const body = shapes.map((s) => s.kind === "rect"
    ? `    { kind: "rect", left: ${s.left}, top: ${s.top}, right: ${s.right}, bottom: ${s.bottom} },`
    : `    { kind: "ellipse", x: ${s.x}, y: ${s.y}, radiusX: ${s.radiusX}, radiusY: ${s.radiusY} },`).join("\n");
  return `  ${file.replace(/\.json$/, "")}: [\n${body}\n  ],`;
});
writeFileSync("lib/stage/world-footprints-data.ts", `// Generated by scripts/build-map-footprints.ts; edit via scripts/map-collision-tool.ts.
// Grounded solids (building bodies, wells, stalls, ponds, rock piles) for the painted
// /maps/<id>.webp locations, in 960×640 world units. Perimeter walls, gates and paths
// stay open by design; world-navigation.test.ts proves every marker stays reachable.
import type { WorldFootprint } from "./world-navigation";

export const PAINTED_MAP_FOOTPRINTS: Readonly<Record<string, readonly WorldFootprint[]>> = {
${entries.join("\n")}
};
`);
console.log(`wrote ${entries.length} maps`);
