/**
 * Give every NPC its own world sprite, derived from its unique painted
 * full-body image (public/npcs/body/<id>.png).
 *
 *   bun scripts/build-npc-sprites.ts
 *
 * The painted bodies are smooth 192 px illustrations; the world is pixel art.
 * Each body is trimmed, reduced to a 72 px-tall sprite (the same native
 * density as the readability-v2 character sheets), quantised to a small
 * palette, given a hard alpha edge and a 1 px dark outline, and written to
 * public/npcs/pixel/<id>.png. lib/world/data/npc-pixel-ids.ts lists the ids.
 */
import sharp from "sharp";
import { mkdirSync, readdirSync, writeFileSync } from "node:fs";

const SRC = "public/npcs/body";
// World sprites match the hero sheets' ~72 px native density; battle sprites
// are shown ~3× larger, so they get a denser 150 px version of the same art.
const VARIANTS = [{ out: "public/npcs/pixel", height: 72, colours: 32 }, { out: "public/npcs/pixel-battle", height: 150, colours: 48 }];
const ids: string[] = [];
for (const { out: OUT } of VARIANTS) mkdirSync(OUT, { recursive: true });
for (const file of readdirSync(SRC).filter((f) => f.endsWith(".png")).sort()) {
  const id = file.replace(/\.png$/, "");
  for (const { out: OUT, height: HEIGHT, colours } of VARIANTS) {
  const trimmed = await sharp(`${SRC}/${file}`).trim({ threshold: 8 }).toBuffer();
  const reduced = await sharp(trimmed).resize({ height: HEIGHT, kernel: "lanczos3" })
    .png({ palette: true, colours, dither: 0 }).toBuffer();
  const { data, info } = await sharp(reduced).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  const w = info.width + 2, h = info.height + 2; // 1 px margin for the outline
  const out = Buffer.alloc(w * h * 4);
  const solid = (x: number, y: number) => x >= 0 && y >= 0 && x < info.width && y < info.height && data[(y * info.width + x) * 4 + 3] >= 110;
  for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) {
    const sx = x - 1, sy = y - 1, o = (y * w + x) * 4;
    if (solid(sx, sy)) {
      const i = (sy * info.width + sx) * 4;
      out[o] = data[i]; out[o + 1] = data[i + 1]; out[o + 2] = data[i + 2]; out[o + 3] = 255;
    } else if (solid(sx - 1, sy) || solid(sx + 1, sy) || solid(sx, sy - 1) || solid(sx, sy + 1)) {
      out[o] = 26; out[o + 1] = 18; out[o + 2] = 12; out[o + 3] = 255;
    }
  }
  await sharp(out, { raw: { width: w, height: h, channels: 4 } }).png().toFile(`${OUT}/${id}.png`);
  }
  ids.push(id);
}
writeFileSync("lib/world/data/npc-pixel-ids.ts", `// Generated by scripts/build-npc-sprites.ts — NPCs with a unique pixel world sprite.
export const NPC_PIXEL_IDS: ReadonlySet<string> = new Set([
${ids.map((id) => `  ${JSON.stringify(id)},`).join("\n")}
]);
`);
console.log(`wrote ${ids.length} NPC sprites × ${VARIANTS.length} sizes`);
