/**
 * Generates the reference pages in docs/reference/ straight from the game
 * data, so the lists and counts in the docs always match the code.
 *
 *   bun scripts/build-docs-reference.ts          # rewrite docs/reference/*.md
 *   bun scripts/build-docs-reference.ts --check  # exit 1 if any page is out of date
 *
 * Rerun after changing content (locations, NPCs, quests, skills, items,
 * recipes, opponents, sects). Pages are plain Markdown tables grouped for
 * browsing; the hand-written guides in docs/ explain the systems.
 */
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  ARTS, EQUIPMENT, SECT_ORDER, SKILLS, SLOT_LABELS, TIERS, WEAPON_FAMILY_LABEL,
  type Art, type Equipment, type EquipSlotType, type Skill,
} from "@/lib/game";
import { artGrid, describeGrid, skillGrid } from "@/lib/game/grid";
import {
  ARTISANS, ENEMY_CATEGORY_LABEL, ITEMS, ITEM_CATEGORIES, ITEM_CATEGORY_LABEL, LIFE_SKILL_ICON, LIFE_SKILL_KEYS,
  LIFE_SKILL_LABEL, LOCATION_MAPS, MASTERY_THRESHOLDS, NPCS, OPPONENTS, QUESTS, RECIPES, RESOURCES, SCENES,
  SECT_HALLS, SECT_MEMBERSHIPS, SHOPS, START_SCENE_ID, TRAIT_LABEL, rankUpGold,
  canPracticeAt, getArtisansAt, getItem, getNpc, getNpcsAtLocation, getOpponent, getResource, getScene,
  getSectHallAt, getShopAt, recipesOfferedBy,
  type Condition, type LocationScene, type QuestDef, type QuestStage, type Scene, type SceneEffect,
} from "@/lib/world";
import { AUTO_MAP_IDS } from "@/lib/world/data/auto-map-ids";
import { LOCATION_ROUTES } from "@/lib/world/data/location-routes";
import { regionOf } from "@/lib/world/data/regions";
import { packMembers } from "@/lib/world/battle-looks";
import { sectLineage } from "@/lib/world/story/registry";
import { FIGHT_EVENTS, fightEventsForLocation, zoneOfLocation } from "@/lib/world/data/random-events";

const OUT_DIR = fileURLToPath(new URL("../docs/reference/", import.meta.url));
const CHECK = process.argv.includes("--check");
const HEADER = "<!-- Generated by scripts/build-docs-reference.ts — do not edit by hand. Rerun the script after changing game data. -->\n\n";

// ── Small helpers ────────────────────────────────────────────────────────
const esc = (s: string | number | undefined | null) => String(s ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");
const code = (s: string) => "`" + s + "`";
function table(head: string[], rows: (string | number)[][]): string {
  if (!rows.length) return "_None._\n";
  return [
    "| " + head.join(" | ") + " |",
    "| " + head.map(() => "---").join(" | ") + " |",
    ...rows.map((r) => "| " + r.map((c) => (typeof c === "number" ? String(c) : c)).join(" | ") + " |"),
  ].join("\n") + "\n";
}
const count = <T,>(xs: readonly T[], key: (x: T) => string) =>
  xs.reduce<Record<string, number>>((acc, x) => { const k = key(x); acc[k] = (acc[k] ?? 0) + 1; return acc; }, {});
const tierName = (ti: number) => `T${ti} ${TIERS[ti]?.n ?? ""}`.trim();
const locations = SCENES.filter((s): s is LocationScene => s.kind === "location");
const locName = (id: string) => { const s = getScene(id); return s?.kind === "location" ? s.name : id; };
const npcName = (id: string | undefined) => (id ? getNpc(id)?.name ?? id : "—");
const skillName = (id: string) => SKILLS.find((s) => s.id === id)?.n ?? id;
const artName = (id: string) => ARTS.find((a) => a.id === id)?.n ?? id;
// ARTS[0] is the "none" placeholder (getArt's fallback), not a learnable art.
const LEARNABLE_ARTS = ARTS.filter((a) => a.id !== "none");

const REGION_LABEL: Record<string, string> = {
  heartland: "heartland", north: "north", south: "south", west: "west", east: "east", jianghu_wild: "wild", global: "global",
};

// Location groups by id prefix (see lib/world/data/world-map.ts).
const GROUPS: { title: string; match: (id: string) => boolean }[] = [
  { title: "Cities", match: (id) => id.startsWith("city_") },
  { title: "Villages, markets and the foothill tutorial area", match: (id) => /^(village|market|tribe)(_|$)|^(tavern)$/.test(id) },
  { title: "Sects", match: (id) => id.startsWith("sect_") },
  { title: "Temples and palaces", match: (id) => /^(temple|palace)_/.test(id) },
  { title: "Villas and mansions", match: (id) => id.startsWith("villa_") },
  { title: "Inns", match: (id) => id.startsWith("inn_") },
  { title: "Homes", match: (id) => id.startsWith("home_") },
  { title: "Mountains, cliffs and peaks", match: (id) => /^(mt|cliff|peak)_/.test(id) },
  { title: "Caves and valleys", match: (id) => /^(cave|valley)_/.test(id) },
  { title: "Isles and waters", match: (id) => /^(isle|sea|pool)_/.test(id) },
  { title: "Frontier and special places", match: () => true },
];
function groupOf(id: string) { return GROUPS.find((g) => g.match(id))!.title; }

function neighbours(loc: LocationScene): string[] {
  const out = new Set<string>();
  for (const ref of loc.routes) {
    const route = getScene(ref.routeSceneId);
    if (route?.kind !== "route") continue;
    for (const d of route.destinations) if (d.locationId !== loc.id) out.add(d.locationId);
  }
  return [...out];
}
function mapKind(id: string) {
  if (LOCATION_MAPS[id]) return "painted (hand-placed markers)";
  if (AUTO_MAP_IDS.has(id)) return "painted (auto layout)";
  return "cards only";
}

// ── Scene effects and conditions in plain words ──────────────────────────
function conditionText(c: Condition): string {
  switch (c.t) {
    case "and": return c.all.map(conditionText).join(" **and** ");
    case "or": return "(" + c.any.map(conditionText).join(" **or** ") + ")";
    case "not":
      if (c.of.t === "anySectMember") return "not an active member of any sect";
      return "not (" + conditionText(c.of) + ")";
    case "gender": return c.equals === "male" ? "male hero" : "female hero";
    case "goldAtLeast": return `at least ${c.amount} gold`;
    case "lifeSkillLevel": return `${LIFE_SKILL_LABEL[c.skill]} (${c.skill}) mastery ≥ ${c.min}`;
    case "learnedArt": return `has learned ${artName(c.artId)} (${code(c.artId)})`;
    case "sectMember": return `active member of ${c.sectId}`;
    case "anySectMember": return "active member of any sect";
    case "sectStatus": return `${c.sectId} membership is ${c.status}`;
    case "sectRankAtLeast": return `${c.sectId} rank ${c.maxRank} or better`;
    case "questStatus": return `quest ${code(c.questId)} is ${c.status}`;
    case "flag": return `flag ${code(c.flag)}${c.equals !== undefined ? " = " + String(c.equals) : ""}`;
    case "trait": {
      const label = TRAIT_LABEL[c.trait];
      if (c.min !== undefined && c.max !== undefined) return `${label} between ${c.min} and ${c.max}`;
      if (c.min !== undefined) return `${label} ≥ ${c.min}`;
      if (c.max !== undefined) return `${label} ≤ ${c.max}`;
      return label;
    }
    case "npcRelationship": return `relationship with ${npcName(c.npcId)}${c.min !== undefined ? " ≥ " + c.min : ""}${c.max !== undefined ? " ≤ " + c.max : ""}`;
    case "hasItem": return `holds ${c.count ?? 1}× ${getItem(c.itemId)?.name ?? c.itemId}`;
    case "defeatedOpponent": return `defeated ${c.count ?? 1}× ${getOpponent(c.opponentId)?.name ?? c.opponentId}`;
    case "visitedLocation": return `visited ${locName(c.locationId)}`;
    case "stoleFromNpc": return `stole from ${npcName(c.npcId)}`;
    case "assassinatedNpc": return `assassinated ${npcName(c.npcId)}`;
    case "kidnappedNpc": return `kidnapped ${npcName(c.npcId)}`;
    default: return code(JSON.stringify(c));
  }
}

/** One word per stage: how it moves forward. */
function stageKind(stage: QuestStage, index: number, quest: QuestDef, sceneAdvance: boolean): string {
  if (stage.objective) {
    const spots = stage.objective.spots;
    const how = spots.some((s) => s.sceneId) ? "scene" : spots.some((s) => s.npcId) ? "person" : "spot";
    return spots.length > 1 ? `objective×${spots.length}` : `objective (${how})`;
  }
  if (stage.autoAdvance) {
    const leaves: string[] = [];
    const walk = (c: Condition) => {
      if (c.t === "and") c.all.forEach(walk);
      else if (c.t === "or") c.any.forEach(walk);
      else if (c.t === "not") walk(c.of);
      else leaves.push({ hasItem: "item", defeatedOpponent: "kill", visitedLocation: "visit", stoleFromNpc: "steal",
        kidnappedNpc: "kidnap", assassinatedNpc: "assassinate", trait: "trait", flag: "flag", questStatus: "quest" }[c.t as string] ?? c.t);
    };
    walk(stage.autoAdvance);
    return [...new Set(leaves)].join("+");
  }
  if (index === quest.stages.length - 1) return "turn-in";
  return sceneAdvance ? "dialog" : "dialog?";
}

function effectsOf(scene: Scene): SceneEffect[] {
  const out: SceneEffect[] = [];
  if (scene.kind === "dialog" || scene.kind === "location") out.push(...(scene.onEnter ?? []));
  if (scene.kind === "dialog") for (const c of scene.choices ?? []) out.push(...(c.effects ?? []));
  if (scene.kind === "route") for (const d of scene.destinations) out.push(...(d.effects ?? []));
  return out;
}
const ALL_EFFECTS = SCENES.flatMap(effectsOf);

// ── Pages ────────────────────────────────────────────────────────────────
const pages: Record<string, string> = {};

// Locations
{
  let md = "# Locations\n\n";
  md += `${locations.length} locations, ${SCENES.filter((s) => s.kind === "route").length} route scenes and ${LOCATION_ROUTES.length} hand-authored connections (\`lib/world/data/location-routes.ts\`). `;
  md += `The game starts at ${code(START_SCENE_ID)}. Map column: *painted (hand-placed markers)* = an entry in \`LOCATION_MAPS\` (\`lib/world/data/location-maps.ts\`); *painted (auto layout)* = listed in \`AUTO_MAP_IDS\` and laid out by \`lib/world/data/auto-maps.ts\`; *cards only* = no painting, the classic card view.\n\n`;
  md += "Services: 🏪 shop · 🏯 martial hall · 🔨 artisans (professions) · 🧘 practice allowed · ⛏ gathering / hunting nodes.\n\n";
  const byGroup = new Map<string, LocationScene[]>();
  for (const loc of locations) { const g = groupOf(loc.id); byGroup.set(g, [...(byGroup.get(g) ?? []), loc]); }
  md += "## Contents\n\n" + GROUPS.filter((g) => byGroup.has(g.title)).map((g) => `- [${g.title}](#${g.title.toLowerCase().replace(/[^a-z0-9 ]/g, "").replace(/ /g, "-")}) (${byGroup.get(g.title)!.length})`).join("\n") + "\n\n";
  for (const g of GROUPS) {
    const locs = byGroup.get(g.title);
    if (!locs) continue;
    md += `## ${g.title}\n\n`;
    md += table(["Id", "Name", "Region", "Map", "People", "Services", "Connects to"], locs.map((loc) => {
      const people = getNpcsAtLocation(loc.id).length + loc.npcs.length;
      const services: string[] = [];
      if (getShopAt(loc.id)) services.push("🏪");
      if (getSectHallAt(loc.id)) services.push("🏯");
      const arts = getArtisansAt(loc.id);
      if (arts.length) services.push("🔨 " + arts.map((a) => a.profession).join(", "));
      if (canPracticeAt(loc)) services.push("🧘");
      const res = (loc.resources ?? []).map((r) => getResource(r.resourceId)?.name ?? r.resourceId);
      if (res.length) services.push("⛏ " + res.join(", "));
      return [code(loc.id), esc(loc.name), REGION_LABEL[regionOf(loc.id)] ?? regionOf(loc.id), mapKind(loc.id), people,
        esc(services.join(" · ")), esc(neighbours(loc).map(locName).join(", "))];
    }));
    md += "\n";
  }
  pages["locations.md"] = md;
}

// Sects
{
  let md = "# Sects\n\n";
  const sectLocs = locations.filter((l) => l.id.startsWith("sect_"));
  const memberships = Object.values(SECT_MEMBERSHIPS);
  md += `${sectLocs.length} sect locations; ${memberships.length} of them run a membership (\`SECT_MEMBERSHIPS\` in \`lib/world/data/sect-memberships.ts\`). `;
  md += "Lower rank numbers are more senior: a member starts at `startRank` and climbs toward `topRank` by spending sect points earned from sect quests; each rank-up pays gold (half the points it costs). Ranks grant no martial arts: every sect skill and art is taught only by its lineage quest (T0–T3) or story saga (T4), and rank gates those quests.\n\n";
  md += table(["Location", "Name", "Membership id", "Registrar", "Ranks", "Sect quests"], sectLocs.map((loc) => {
    const def = memberships.find((m) => m.hallLocationId === loc.id);
    const quests = def ? QUESTS.filter((q) => q.sectId === def.id) : [];
    return [code(loc.id), esc(loc.name), def ? code(def.id) : "— (no membership)", def ? esc(npcName(def.registrarNpcId)) : "—",
      def ? `${def.startRank} → ${def.topRank}` : "—", def ? quests.length : "—"];
  }));
  md += "\n";
  for (const def of memberships) {
    const quests = QUESTS.filter((q) => q.sectId === def.id);
    md += `## ${esc(def.name)} (${code(def.id)})\n\n`;
    md += `- Hall: ${esc(locName(def.hallLocationId))} (${code(def.hallLocationId)}) · registrar: ${esc(npcName(def.registrarNpcId))} (${code(def.registrarNpcId)})\n`;
    md += `- Join requirements: ${conditionText(def.joinRequirements)}\n`;
    md += `- Ranks: start ${def.startRank}, top ${def.topRank} · quest cooldown ${def.questCooldownDays} days\n`;
    const costs: string[] = [];
    for (let r = def.startRank - 1; r >= def.topRank; r--) costs.push(`→${r}: ${def.rankUpCost(r)}`);
    md += `- Rank-up cost (sect points): ${costs.join(" · ") || "—"}\n`;
    md += `- Sect quests: ${quests.length} (${quests.filter((q) => q.isArtQuest).length} art quests)` +
      (QUESTS.some((q) => q.id === `qst_${def.id}_redemption`) ? ` · redemption quest ${code(`qst_${def.id}_redemption`)}` : "") +
      (OPPONENTS.some((o) => o.id === `hunter_${def.id}`) ? ` · betrayal hunter ${code(`hunter_${def.id}`)}` : "") + "\n\n";
    md += `- Rank-up gold: ${(() => { const g: string[] = []; for (let r = def.startRank - 1; r >= def.topRank; r--) g.push(`→${r}: ${rankUpGold(def, r)}`); return g.join(" · ") || "—"; })()}\n\n`;
    md += "Martial line — every skill and art is taught only by its lineage quest or saga:\n\n";
    md += table(["Rank", "Kind", "Skill / art", "Quest"], sectLineage(def.name).map((e) => [e.rank ?? "—", e.kind,
      esc(`${e.kind === "skill" ? skillName(e.id) : artName(e.id)} (${code(e.id)})`),
      e.arcId ? `saga ${code(e.arcId)}` : code(e.questId)]));
    md += "\n";
  }
  pages["sects.md"] = md;
}

// Quests
{
  const advanceBeats = new Set(ALL_EFFECTS.filter((e) => e.t === "advanceQuest").map((e) => (e as { questId: string }).questId));
  const hasScene = (id: string) => !!getScene(id);
  let md = "# Quests\n\n";
  const main = QUESTS.filter((q) => (q.type ?? "main") === "main" && !q.sectId);
  const sect = QUESTS.filter((q) => q.sectId);
  const side = QUESTS.filter((q) => q.type === "side" && !q.sectId);
  const stages = QUESTS.flatMap((q) => q.stages);
  md += `${QUESTS.length} quests: ${main.length} main, ${side.length} side, ${sect.length} sect quests (${sect.filter((q) => q.isArtQuest).length} of them art quests). `;
  md += `${QUESTS.filter((q) => q.isMajor).length} are marked \`isMajor\` (completing one spreads a rumor about the hero). `;
  md += `${stages.length} stages in total: ${stages.filter((s) => s.autoAdvance).length} advance on their own (\`autoAdvance\`), ${stages.filter((s) => s.objective).length} are hands-on objectives (\`objective\`), the rest are dialog beats or the final hand-in. `;
  md += `${QUESTS.filter((q) => hasScene(`qs_${q.id}_offer`)).length} quests have an offer scene (\`qs_<id>_offer\`) and ${QUESTS.filter((q) => hasScene(`qs_${q.id}_complete`)).length} a completion scene (\`qs_<id>_complete\`).\n\n`;
  md += "Stage kinds: **item** / **kill** / **visit** / **steal** / **kidnap** / **assassinate** / **trait** / **flag** = `autoAdvance` condition types · **objective** = map spot, person or scene the hero uses in person (`stage.objective`, ×n = several spots) · **dialog** = advanced by an `advanceQuest` choice in a scene · **turn-in** = last stage, closed at the turn-in person or by the completion scene.\n\n";
  const row = (q: QuestDef) => [code(q.id), esc(q.name), esc(npcName(q.giverNpcId)),
    esc(q.stages.map((s, i) => stageKind(s, i, q, advanceBeats.has(q.id))).join(" → ")),
    [q.isMajor ? "major" : "", q.isArtQuest ? "art" : "", q.minSectRank !== undefined ? `rank ≤ ${q.minSectRank}` : "", q.prereqs ? "prereqs" : ""].filter(Boolean).join(", ")];
  const head = ["Id", "Name", "Giver", "Stages", "Notes"];
  md += "## Contents\n\n- [Main quests](#main-quests)\n- [Sect quests](#sect-quests)\n- [Side quests by the giver's home](#side-quests-by-the-givers-home)\n\n";
  md += "## Main quests\n\n" + table(head, main.map(row)) + "\n";
  md += "## Sect quests\n\n";
  const bySect = new Map<string, QuestDef[]>();
  for (const q of sect) bySect.set(q.sectId!, [...(bySect.get(q.sectId!) ?? []), q]);
  for (const [sectId, qs] of bySect) md += `### ${esc(SECT_MEMBERSHIPS[sectId as keyof typeof SECT_MEMBERSHIPS]?.name ?? sectId)} (${code(sectId)})\n\n` + table(head, qs.map(row)) + "\n";
  md += "## Side quests by the giver's home\n\n";
  const byHome = new Map<string, QuestDef[]>();
  for (const q of side) {
    const home = getNpc(q.giverNpcId ?? "")?.locationIds[0] ?? "(no giver)";
    byHome.set(home, [...(byHome.get(home) ?? []), q]);
  }
  for (const [home, qs] of [...byHome].sort((a, b) => locName(a[0]).localeCompare(locName(b[0]), "th"))) {
    md += `### ${esc(locName(home))} (${code(home)})\n\n` + table(head, qs.map(row)) + "\n";
  }
  pages["quests.md"] = md;
}

// NPCs
{
  let md = "# People (NPCs)\n\n";
  md += `${NPCS.length} registry NPCs (\`lib/world/data/npcs/\`). Capabilities: 💬 talk (\`dialogSceneId\`) · ⚔ spar (\`sparOpponentId\`, non-fatal) · 🤏 can be robbed (\`stealLoot\`) · 📜 quests offered or turned in. `;
  md += "An NPC listed at several places is shown under each.\n\n";
  const byLoc = new Map<string, typeof NPCS[number][]>();
  for (const npc of NPCS) for (const loc of npc.locationIds) byLoc.set(loc, [...(byLoc.get(loc) ?? []), npc]);
  const unplaced = NPCS.filter((n) => !n.locationIds.length);
  for (const g of GROUPS) {
    const locs = locations.filter((l) => groupOf(l.id) === g.title && byLoc.has(l.id));
    if (!locs.length) continue;
    md += `## ${g.title}\n\n`;
    for (const loc of locs) {
      md += `### ${esc(loc.name)} (${code(loc.id)})\n\n`;
      md += table(["Id", "Name", "Can", "Quests"], byLoc.get(loc.id)!.map((n) => {
        const quests = QUESTS.filter((q) => q.giverNpcId === n.id || q.turnInNpcId === n.id).length;
        const can = [n.dialogSceneId ? "💬" : "", n.sparOpponentId ? "⚔" : "", n.stealLoot?.length ? "🤏" : ""].filter(Boolean).join(" ");
        return [code(n.id), esc(n.name), can || "—", quests || "—"];
      }));
      md += "\n";
    }
  }
  if (unplaced.length) md += "## Not placed on the map\n\n" + table(["Id", "Name"], unplaced.map((n) => [code(n.id), esc(n.name)])) + "\n";
  pages["npcs.md"] = md;
}

// Skills, arts, equipment
{
  let md = "# Martial arts and equipment\n\n";
  const tiers = count(SKILLS, (s) => tierName(s.ti));
  md += `${SKILLS.length} move skills (\`lib/game/data/skills.ts\`), ${LEARNABLE_ARTS.length} inner arts (\`lib/game/data/arts.ts\`, not counting the \`none\` placeholder) and ${EQUIPMENT.length} pieces of equipment (\`lib/game/data/equipment.ts\`).\n\n`;
  md += "Move skills per tier: " + Object.entries(tiers).map(([k, v]) => `${k}: ${v}`).join(" · ") + ".\n\n";
  md += "Grid column: the skill's range and area on the tactics board (`skillGrid` / `artGrid` + `describeGrid` in `lib/game/grid/skill-grid.ts`). Weapon families: " +
    Object.entries(WEAPON_FAMILY_LABEL).map(([k, v]) => `${code(k)} ${esc(v)}`).join(" · ") + ".\n\n";
  md += "## Contents\n\n- [Move skills by sect](#move-skills-by-sect)\n- [Inner arts by sect](#inner-arts-by-sect)\n- [Equipment by slot](#equipment-by-slot)\n\n";
  const sectOrder = (sc: string) => { const i = SECT_ORDER.indexOf(sc); return i < 0 ? 999 : i; };
  const sects = [...new Set([...SKILLS.map((s) => s.sc), ...LEARNABLE_ARTS.map((a) => a.sc)])].sort((a, b) => sectOrder(a) - sectOrder(b));
  md += "## Move skills by sect\n\n";
  for (const sc of sects) {
    const list = SKILLS.filter((s) => s.sc === sc).sort((a, b) => a.ti - b.ti);
    if (!list.length) continue;
    md += `### ${esc(sc)} (${list.length})\n\n`;
    md += table(["Id", "Name", "Tier", "Weapon", "Attack", "bp", "Hits", "Grid", "Types"], list.map((s: Skill) => [
      code(s.id), esc(s.n), tierName(s.ti), s.w, s.at === "int" ? "internal" : s.at === "phy" ? "physical" : "—", s.bp, s.hits ?? 1,
      esc(describeGrid(skillGrid(s))), (s.types ?? []).join(", ") || "—"]));
    md += "\n";
  }
  md += "## Inner arts by sect\n\n";
  for (const sc of sects) {
    const list = LEARNABLE_ARTS.filter((a) => a.sc === sc).sort((a, b) => a.ti - b.ti);
    if (!list.length) continue;
    md += `### ${esc(sc)} (${list.length})\n\n`;
    md += table(["Id", "Name", "Tier", "Active", "Grid", "Passive", "HP/MP per level", "Types"], list.map((a: Art) => {
      const grid = artGrid(a);
      return [code(a.id), esc(a.n), tierName(a.ti), a.act ? `${esc(a.act.n)} (${a.act.t}, ${a.act.c} MP, cd ${a.act.cd})` : "—",
        grid ? esc(describeGrid(grid)) : "—", a.pas ? `${a.pas.tr} ${a.pas.ch}% → ${a.pas.e.t}` : "—", `${a.hL} / ${a.mL}`,
        (a.types ?? []).join(", ") || "—"];
    }));
    md += "\n";
  }
  md += "## Equipment by slot\n\n";
  const bonus = (e: Equipment) => {
    const parts: [string, number | undefined][] = [["ATK", e.atkb], ["PA", e.pab], ["IA", e.iab], ["PD", e.pdb], ["ID", e.idb], ["HP", e.hpb],
      ["MP", e.mpb], ["SPD", e.spdb], ["Eva", e.evab], ["Acc", e.accb], ["Cri", e.crib], ["Res", e.resb]];
    return parts.filter(([, v]) => v).map(([k, v]) => `${k} +${v}`).join(", ") || "—";
  };
  for (const slot of Object.keys(SLOT_LABELS) as EquipSlotType[]) {
    const list = EQUIPMENT.filter((e) => e.ty === slot);
    md += `### ${esc(SLOT_LABELS[slot])} (${code(slot)}, ${list.length})\n\n`;
    md += table(["Id", "Name", "Bonuses", "Effect"], list.map((e) => [code(e.id), esc(e.n), bonus(e),
      e.eff ? code(JSON.stringify(e.eff)) + (e.instrument ? " · instrument" : "") : e.instrument ? "instrument" : "—"]));
    md += "\n";
  }
  pages["martial-arts.md"] = md;
}

// Items, shops, crafting, gathering
{
  let md = "# Items, shops, crafting and gathering\n\n";
  md += `${ITEMS.length} items (\`lib/world/data/items.ts\`), ${SHOPS.length} shops, ${SECT_HALLS.length} martial halls, ${ARTISANS.length} artisans, ${RECIPES.length} recipes and ${RESOURCES.length} gathering / hunting nodes.\n\n`;
  md += "## Contents\n\n- [Items by category](#items-by-category)\n- [Shops](#shops)\n- [Martial halls](#martial-halls)\n- [Artisans](#artisans)\n- [Recipes by profession](#recipes-by-profession)\n- [Gathering and hunting nodes](#gathering-and-hunting-nodes)\n- [Life skills](#life-skills)\n\n";
  md += "## Items by category\n\n";
  const useText = (u: (typeof ITEMS)[number]["use"]) => {
    if (!u) return "—";
    switch (u.t) {
      case "heal": return `heal${u.hp ? ` HP ${u.hp}` : ""}${u.mp ? ` MP ${u.mp}` : ""}`;
      case "trainSkill": return `train ${u.skill} +${u.xp} xp`;
      case "manualLearnSkill": return `learn ${esc(skillName(u.skillId))} (${u.reqStat} ≥ ${u.reqValue})`;
      case "manualLearnArt": return `learn ${esc(artName(u.artId))} (${u.reqStat} ≥ ${u.reqValue})`;
      case "learnMeridian": return `learn meridian chart ${code(u.chartId)}`;
    }
  };
  for (const cat of ITEM_CATEGORIES) {
    const list = ITEMS.filter((i) => (i.category ?? "misc") === cat);
    if (!list.length) continue;
    md += `### ${esc(ITEM_CATEGORY_LABEL[cat])} (${code(cat)}, ${list.length})\n\n`;
    md += table(["Id", "Name", "Price", "Use"], list.map((i) => [code(i.id), esc(i.name), i.price ?? 0, useText(i.use)]));
    md += "\n";
  }
  md += "## Shops\n\n" + table(["Location", "Shop", "Items for sale", "Buys", "Sell-back"], SHOPS.map((s) => [
    `${esc(locName(s.locationId))} (${code(s.locationId)})`, esc(s.label), s.inventory.length,
    s.acceptsCategories?.length ? s.acceptsCategories.join(", ") : "everything", `×${s.sellMultiplier}`])) + "\n";
  md += "## Martial halls\n\nCity halls teach tier 0–1 ยุทธจักร skills and arts for gold (`lib/world/data/sect-halls.ts`).\n\n";
  md += table(["Location", "Hall", "Skills", "Arts"], SECT_HALLS.map((h) => [
    `${esc(locName(h.locationId))} (${code(h.locationId)})`, esc(h.label),
    esc(h.offers.filter((o) => o.kind === "skill").map((o) => `${skillName(o.id)} ${o.price}g`).join(", ") || "—"),
    esc(h.offers.filter((o) => o.kind === "art").map((o) => `${artName(o.id)} ${o.price}g`).join(", ") || "—")])) + "\n";
  md += "## Artisans\n\nEvery city hosts all six craft professions; villages and some sects host one. Recipes marked basic are taught by every artisan of the profession (`recipesOfferedBy`).\n\n";
  md += table(["Location", "Profession", "Artisan", "Recipes taught", "Specialties"], ARTISANS.map((a) => {
    const offered = recipesOfferedBy(a);
    return [`${esc(locName(a.locationId))} (${code(a.locationId)})`, `${LIFE_SKILL_ICON[a.profession] ?? ""} ${a.profession}`, esc(a.npcName),
      offered.length, esc(a.recipes.map((r) => RECIPES.find((x) => x.id === r.recipeId)?.name ?? r.recipeId).join(", ") || "—")];
  })) + "\n";
  md += "## Recipes by profession\n\n";
  const recipeSkills = [...new Set(RECIPES.map((r) => r.skill ?? "(none)"))];
  for (const skill of recipeSkills) {
    const list = RECIPES.filter((r) => (r.skill ?? "(none)") === skill);
    md += `### ${esc(LIFE_SKILL_LABEL[skill as keyof typeof LIFE_SKILL_LABEL] ?? skill)} (${code(skill)}, ${list.length})\n\n`;
    md += table(["Id", "Name", "Inputs → output", "Mastery", "Basic", "Taught at"], list.map((r) => {
      const at = ARTISANS.filter((a) => recipesOfferedBy(a).some((o) => o.recipeId === r.id)).map((a) => locName(a.locationId));
      return [code(r.id), esc(r.name),
        esc(r.inputs.map((i) => `${i.count}× ${getItem(i.itemId)?.name ?? i.itemId}`).join(" + ") + ` → ${r.output.count}× ${getItem(r.output.itemId)?.name ?? r.output.itemId}`),
        r.requiredMastery ?? 1, r.basic ? "yes" : "", esc(at.length > 4 ? `${at.length} artisans` : at.join(", ") || "anywhere (not artisan-gated)")];
    }));
    md += "\n";
  }
  md += "## Gathering and hunting nodes\n\n";
  md += table(["Id", "Name", "Life skill", "Level", "Stamina", "Yields", "Found at"], RESOURCES.map((r) => {
    const at = locations.filter((l) => (l.resources ?? []).some((n) => n.resourceId === r.id)).map((l) => l.name);
    const yields = r.yields.map((y) => getItem(y.itemId)?.name ?? y.itemId).join(", ");
    return [code(r.id), esc(r.name), r.skill, r.level, r.staminaCost,
      esc(yields + (r.goldYield ? ` · gold ${r.goldYield[0]}–${r.goldYield[1]}` : "") + (r.opponentIds?.length ? ` · fights: ${r.opponentIds.map((o) => getOpponent(o)?.name ?? o).join(", ")}` : "")),
      esc(at.length > 6 ? `${at.length} places` : at.join(", ") || "—")];
  })) + "\n";
  md += "## Life skills\n\n";
  md += `Mastery levels 1–5 at xp thresholds ${MASTERY_THRESHOLDS.join(" / ")} (\`lib/world/data/life-skills.ts\`).\n\n`;
  md += table(["Key", "Name", "Icon", "Nodes", "Recipes"], LIFE_SKILL_KEYS.map((k) => [code(k), esc(LIFE_SKILL_LABEL[k]), LIFE_SKILL_ICON[k] ?? "",
    RESOURCES.filter((r) => r.skill === k).length, RECIPES.filter((r) => r.skill === k).length])) + "\n";
  pages["items-and-crafting.md"] = md;
}

// Opponents
{
  let md = "# Opponents\n\n";
  const roaming = new Map<string, Set<string>>();
  for (const loc of locations) for (const ev of fightEventsForLocation(loc.id)) {
    const zones = roaming.get(ev.opponentId) ?? new Set<string>();
    zones.add(zoneOfLocation(loc.id));
    roaming.set(ev.opponentId, zones);
  }
  const questFights = count(ALL_EFFECTS.filter((e) => e.t === "triggerBattle"), (e) => (e as { opponentId: string }).opponentId);
  md += `${OPPONENTS.length} opponents (\`lib/world/data/opponents.ts\`). Foes that turn up on the map while the hero walks come from ${FIGHT_EVENTS.length} fight events filtered by zone (\`lib/world/data/random-events.ts\`).\n\n`;
  md += "Met via: **roams** = turns up on the map in the listed zones while the hero walks · **hunt** = a hunting node · **spar** = an NPC's practice bout · **scene** = a quest or story battle (count of scene choices) · **law** = pursuers after wanted marks · **betrayal** = hunters after betraying a sect.\n\n";
  const byTier = count(OPPONENTS, (o) => `T${o.ti ?? 0}`);
  const byCat = count(OPPONENTS, (o) => o.category ?? "human");
  md += "Per tier: " + Object.entries(byTier).sort().map(([k, v]) => `${k}: ${v}`).join(" · ") + ". Per category: " +
    Object.entries(byCat).map(([k, v]) => `${ENEMY_CATEGORY_LABEL[k as keyof typeof ENEMY_CATEGORY_LABEL] ?? k} (${k}): ${v}`).join(" · ") + ".\n\n";
  for (let ti = 0; ti <= 4; ti++) {
    const list = OPPONENTS.filter((o) => (o.ti ?? 0) === ti);
    if (!list.length) continue;
    md += `## Tier ${ti} (${list.length})\n\n`;
    md += table(["Id", "Name", "Category", "Pack", "Drops", "Met via"], list.map((o) => {
      const via: string[] = [];
      const zones = roaming.get(o.id);
      if (zones) via.push(`roams (${[...zones].sort().join(", ")})`);
      if (RESOURCES.some((r) => r.opponentIds?.includes(o.id))) via.push("hunt");
      if (NPCS.some((n) => n.sparOpponentId === o.id)) via.push("spar");
      if (questFights[o.id]) via.push(`scene ×${questFights[o.id]}`);
      if (o.id.startsWith("law_")) via.push("law");
      if (o.id.startsWith("hunter_")) via.push("betrayal");
      return [code(o.id), esc(o.name), o.category ?? "human", packMembers(o).map((m) => `${m.count}× ${esc(getOpponent(m.opponentId)?.name ?? m.opponentId)}`).join(" + ") || "—",
        o.drops?.length ?? 0, via.join(", ") || "—"];
    }));
    md += "\n";
  }
  pages["opponents.md"] = md;
}

// Index with totals
{
  const count2 = (kind: Scene["kind"]) => SCENES.filter((s) => s.kind === kind).length;
  let md = "# Reference\n\nGenerated lists of everything in the game, taken straight from the data tables. Counts here are exact for the commit they were generated at.\n\n";
  md += table(["Page", "What it lists"], [
    ["[Locations](locations.md)", "every place: region, map, people, services, connections"],
    ["[Sects](sects.md)", "sect locations, memberships, join rules, rank costs, reward pools"],
    ["[Quests](quests.md)", "every quest with giver and how each stage advances"],
    ["[People](npcs.md)", "every NPC by place, with talk / spar / steal / quest capabilities"],
    ["[Martial arts and equipment](martial-arts.md)", "move skills, inner arts (with grid range) and equipment"],
    ["[Items, shops, crafting and gathering](items-and-crafting.md)", "items, shops, halls, artisans, recipes, resource nodes, life skills"],
    ["[Opponents](opponents.md)", "every foe by tier, with pack, drops and where it is met"],
  ]);
  md += "\n## Totals\n\n";
  md += table(["Content", "Count"], [
    ["Locations", locations.length], ["Route scenes", count2("route")], ["Dialog scenes", count2("dialog")], ["All scenes", SCENES.length],
    ["Location connections (`LOCATION_ROUTES`)", LOCATION_ROUTES.length],
    ["Painted maps (hand-placed / auto layout)", `${locations.filter((l) => LOCATION_MAPS[l.id]).length} / ${locations.filter((l) => !LOCATION_MAPS[l.id] && AUTO_MAP_IDS.has(l.id)).length}`],
    ["Sect locations / memberships", `${locations.filter((l) => l.id.startsWith("sect_")).length} / ${Object.keys(SECT_MEMBERSHIPS).length}`],
    ["NPCs", NPCS.length], ["Quests", QUESTS.length], ["Quest stages", QUESTS.reduce((n, q) => n + q.stages.length, 0)],
    ["Move skills / inner arts / equipment", `${SKILLS.length} / ${LEARNABLE_ARTS.length} / ${EQUIPMENT.length}`],
    ["Items", ITEMS.length], ["Shops / martial halls / artisans", `${SHOPS.length} / ${SECT_HALLS.length} / ${ARTISANS.length}`],
    ["Recipes", RECIPES.length], ["Gathering and hunting nodes", RESOURCES.length], ["Life skills", LIFE_SKILL_KEYS.length],
    ["Opponents", OPPONENTS.length], ["Roaming foe events", FIGHT_EVENTS.length],
  ]);
  md += "\nRegenerate with `bun scripts/build-docs-reference.ts`; `--check` fails when a page is stale.\n";
  pages["README.md"] = md;
}

// ── Write or check ───────────────────────────────────────────────────────
mkdirSync(OUT_DIR, { recursive: true });
const stale: string[] = [];
for (const [file, body] of Object.entries(pages)) {
  const path = join(OUT_DIR, file);
  const text = HEADER + body.trimEnd() + "\n";
  if (CHECK) {
    if (!existsSync(path) || readFileSync(path, "utf8") !== text) stale.push(file);
  } else {
    writeFileSync(path, text);
  }
}
if (CHECK) {
  if (stale.length) { console.error(`docs/reference is out of date: ${stale.join(", ")} — run bun scripts/build-docs-reference.ts`); process.exit(1); }
  console.log(`docs/reference is up to date (${Object.keys(pages).length} pages)`);
} else {
  console.log(`wrote ${Object.keys(pages).length} pages to docs/reference/`);
}
