// One-shot splitter for the sects-temples.ts trio (quests, npcs,
// scenes-content). Reads the source file, walks every top-level entry,
// groups by sect-id (via sectId / giverNpcId / locationIds / scene id
// prefix depending on the file), and writes per-sect files into
// `<dir>/sects/<sectId>.ts`. Original file is rewritten as a barrel
// that imports + re-exports the same constant so callers keep working.
//
// Run: `bun scripts/split-sects-file.ts [quests|npcs|scenes]`
//
// Each rule returns either a known sectId (string) OR `null` for
// "doesn't fit a sect" — those entries go into `_other.ts`.

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import path from "node:path";

const META_DIR = (import.meta as unknown as { dir: string }).dir;
const ROOT = path.resolve(META_DIR, "..");

// Sect IDs we recognise — order drives output file ordering in the barrel.
const KNOWN_SECTS = [
  "shaolin", "wudang", "emei", "huashan", "songshan", "taishan",
  "hengshan", "quanzhen", "gumu", "lingjiu", "beggars", "ming",
  "xiaoyao", "xingxiu", "wudu", "xuedao", "jinyiwei", "tang",
  "kunlun", "xueyu", "sunmoon",
];

interface FileSpec {
  source: string;
  exportName: string;
  itemType: string; // TS type e.g. "QuestDef" — used in the barrel
  importTypePath: string; // e.g. "../../types"
  // Pull a sectId out of an entry's text. null = goes into _other.
  detect: (entry: string) => string | null;
}

const SPECS: Record<string, FileSpec> = {
  quests: {
    source: "lib/world/data/quests/sects-temples.ts",
    exportName: "QUESTS_SECTS_TEMPLES",
    itemType: "QuestDef",
    importTypePath: "../../../types",
    detect: (entry) => {
      const sectMatch = entry.match(/sectId:\s*"([^"]+)"/);
      if (sectMatch && KNOWN_SECTS.includes(sectMatch[1]!)) return sectMatch[1]!;
      const giver = entry.match(/giverNpcId:\s*"sect_([a-z_]+?)_/);
      if (giver && KNOWN_SECTS.includes(giver[1]!)) return giver[1]!;
      const turnIn = entry.match(/turnInNpcId:\s*"sect_([a-z_]+?)_/);
      if (turnIn && KNOWN_SECTS.includes(turnIn[1]!)) return turnIn[1]!;
      // Quest id sometimes carries the sect (qst_<sect>_*).
      const qid = entry.match(/id:\s*"qst_([a-z]+)_/);
      if (qid && KNOWN_SECTS.includes(qid[1]!)) return qid[1]!;
      return null;
    },
  },
  npcs: {
    source: "lib/world/data/npcs/sects-temples.ts",
    exportName: "NPCS_SECTS_TEMPLES",
    itemType: "NpcDef",
    importTypePath: "../../../types",
    detect: (entry) => {
      const loc = entry.match(/locationIds:\s*\[\s*"sect_([a-z_]+)"/);
      if (loc && KNOWN_SECTS.includes(loc[1]!)) return loc[1]!;
      // Fallback: id pattern
      const id = entry.match(/id:\s*"sect_([a-z]+)_/);
      if (id && KNOWN_SECTS.includes(id[1]!)) return id[1]!;
      return null;
    },
  },
  scenes: {
    source: "lib/world/data/scenes-content/sects-temples.ts",
    exportName: "SCENES_SECTS_TEMPLES",
    itemType: "Scene",
    importTypePath: "../../../types",
    detect: (entry) => {
      // Scene ids: npc_sect_<sect>_<rest>_talk OR qs_qst_<sect>_<rest>
      const npc = entry.match(/id:\s*"npc_sect_([a-z]+)_/);
      if (npc && KNOWN_SECTS.includes(npc[1]!)) return npc[1]!;
      const qs = entry.match(/id:\s*"qs_qst_([a-z]+)_/);
      if (qs && KNOWN_SECTS.includes(qs[1]!)) return qs[1]!;
      return null;
    },
  },
};

// Walk an array body and split into top-level entries — same logic as
// the sort script, but here we also keep ATTACHED LEAD COMMENTS so
// header context comes along when an entry moves to its sect file.
function splitEntries(body: string): string[] {
  const entries: string[] = [];
  let depth = 0;
  let start = -1;
  let inStr: string | null = null;
  for (let i = 0; i < body.length; i++) {
    const c = body[i]!;
    const next = body[i + 1];
    if (inStr) {
      if (c === "\\") { i++; continue; }
      if (c === inStr) inStr = null;
      continue;
    }
    if (c === "/" && next === "/") {
      while (i < body.length && body[i] !== "\n") i++;
      continue;
    }
    if (c === "/" && next === "*") {
      i += 2;
      while (i < body.length - 1 && !(body[i] === "*" && body[i + 1] === "/")) i++;
      i++;
      continue;
    }
    if (c === '"' || c === "'" || c === "`") { inStr = c; continue; }
    if (c === "{") {
      // Just mark the entry start — leading comments are dropped during
      // the split (they live in dead space between entries and would be
      // tricky to attribute correctly across sect boundaries). Per-sect
      // file headers are regenerated by the writer.
      if (depth === 0) start = i;
      depth++;
    } else if (c === "}") {
      depth--;
      if (depth === 0 && start >= 0) {
        let end = i + 1;
        while (end < body.length && (body[end] === "," || body[end] === " ")) end++;
        entries.push(body.slice(start, end).replace(/,\s*$/, "").trimEnd());
        start = -1;
      }
    }
  }
  return entries;
}

function findArrayBody(src: string, declaration: string): { open: number; close: number; preamble: string } {
  const declIdx = src.indexOf(declaration);
  if (declIdx < 0) throw new Error(`declaration not found: ${declaration}`);
  const eqIdx = src.indexOf("=", declIdx);
  const open = src.indexOf("[", eqIdx);
  let depth = 0;
  for (let i = open; i < src.length; i++) {
    const c = src[i]!;
    if (c === "[") depth++;
    else if (c === "]") {
      depth--;
      if (depth === 0) return { open, close: i, preamble: src.slice(0, declIdx) };
    }
  }
  throw new Error("array close not found");
}

function splitFile(spec: FileSpec): void {
  const fullPath = path.join(ROOT, spec.source);
  let src = readFileSync(fullPath, "utf8");
  // Strip the original `import type { ... }` line — the barrel writer
  // re-emits it. Without this strip, the file ends up with two copies
  // and TS errors on duplicate identifier.
  src = src.replace(/^import type \{[^}]+\}[^;]*;\s*\n/m, "");
  const { open, close, preamble } = findArrayBody(src, `export const ${spec.exportName}`);
  const body = src.slice(open + 1, close);
  const entries = splitEntries(body);

  const buckets = new Map<string, string[]>();
  for (const e of entries) {
    const sect = spec.detect(e) ?? "_other";
    const list = buckets.get(sect) ?? [];
    list.push(e);
    buckets.set(sect, list);
  }

  // Sort sects: KNOWN_SECTS order first, then _other last.
  const orderedSects: string[] = [];
  for (const s of KNOWN_SECTS) if (buckets.has(s)) orderedSects.push(s);
  for (const s of buckets.keys()) {
    if (!orderedSects.includes(s) && s !== "_other") orderedSects.push(s);
  }
  if (buckets.has("_other")) orderedSects.push("_other");

  const dir = path.dirname(fullPath);
  const sectsDir = path.join(dir, "sects");
  if (!existsSync(sectsDir)) mkdirSync(sectsDir, { recursive: true });

  // Write per-sect files.
  for (const sect of orderedSects) {
    const items = buckets.get(sect)!;
    const constName = `${spec.exportName.replace(/_SECTS_TEMPLES$/, "")}_${sect.toUpperCase()}`;
    const fileBody =
      `import type { ${spec.itemType} } from "${spec.importTypePath}";\n\n` +
      `// Auto-split from sects-temples.ts by scripts/split-sects-file.ts.\n` +
      `// Edit individual entries here; the barrel file (../sects-temples.ts)\n` +
      `// re-exports the concatenated array so callers keep working.\n\n` +
      `export const ${constName}: readonly ${spec.itemType}[] = [\n` +
      items.map((e) => `  ${e},`).join("\n\n") +
      `\n];\n`;
    writeFileSync(path.join(sectsDir, `${sect}.ts`), fileBody, "utf8");
  }

  // Rewrite original as a barrel.
  const importNames = orderedSects.map(
    (s) => `${spec.exportName.replace(/_SECTS_TEMPLES$/, "")}_${s.toUpperCase()}`,
  );
  const barrel =
    preamble +
    `import type { ${spec.itemType} } from "${spec.importTypePath.replace("../../../", "../../")}";\n` +
    orderedSects
      .map((s, i) => `import { ${importNames[i]} } from "./sects/${s}";`)
      .join("\n") +
    `\n\n// Barrel for the sect content split. Per-sect files live in\n` +
    `// ./sects/<sectId>.ts. Adding a new sect = create a new file +\n` +
    `// add the import + spread below.\n` +
    `export const ${spec.exportName}: readonly ${spec.itemType}[] = [\n` +
    importNames.map((n) => `  ...${n},`).join("\n") +
    `\n];\n`;
  writeFileSync(fullPath, barrel, "utf8");

  console.log(
    `[split] ${spec.source} → ${entries.length} entries · ${orderedSects.length} files`,
  );
  for (const s of orderedSects) {
    console.log(`  ${s.padEnd(12)} ${buckets.get(s)!.length} entries`);
  }
}

const arg = process.argv[2];
const targets = arg ? [arg] : Object.keys(SPECS);
for (const t of targets) {
  const spec = SPECS[t];
  if (!spec) {
    console.error(`unknown target: ${t}`);
    process.exit(1);
  }
  splitFile(spec);
}
