// Generated by scripts/build-anim-sheets.ts — do not edit by hand.
import type { AnimSheet } from "./anim-sheets";

export const ANIM_SHEET_DATA: Record<string, AnimSheet> = {
  "boss_golden_serpent": {
    "id": "boss_golden_serpent",
    "url": "/art/anims/boss_golden_serpent.png?v=d68810c0",
    "frameW": 193,
    "frameH": 165,
    "feetY": 0.994,
    "facing": "right",
    "scale": 2.3,
    "clips": {
      "idle": {
        "row": 0,
        "frames": 8,
        "fps": 7
      },
      "attack": {
        "row": 1,
        "frames": 8,
        "fps": 11
      },
      "hurt": {
        "row": 2,
        "frames": 5,
        "fps": 9
      }
    }
  },
  "boss_blood_tiger": {
    "id": "boss_blood_tiger",
    "url": "/art/anims/boss_blood_tiger.png?v=1445f72e",
    "frameW": 180,
    "frameH": 125,
    "feetY": 0.992,
    "facing": "right",
    "scale": 2.2,
    "clips": {
      "idle": {
        "row": 0,
        "frames": 8,
        "fps": 7
      },
      "attack": {
        "row": 1,
        "frames": 8,
        "fps": 11
      },
      "hurt": {
        "row": 2,
        "frames": 4,
        "fps": 8
      }
    }
  },
  "boss_sword_eagle": {
    "id": "boss_sword_eagle",
    "url": "/art/anims/boss_sword_eagle.png?v=957bae1b",
    "frameW": 201,
    "frameH": 167,
    "feetY": 0.988,
    "facing": "right",
    "scale": 2.4,
    "clips": {
      "idle": {
        "row": 0,
        "frames": 6,
        "fps": 6
      },
      "attack": {
        "row": 1,
        "frames": 8,
        "fps": 11
      },
      "hurt": {
        "row": 2,
        "frames": 5,
        "fps": 9
      }
    }
  },
  "boss_sun_turtle": {
    "id": "boss_sun_turtle",
    "url": "/art/anims/boss_sun_turtle.png?v=1ec91559",
    "frameW": 203,
    "frameH": 153,
    "feetY": 0.987,
    "facing": "right",
    "scale": 2.6,
    "clips": {
      "idle": {
        "row": 0,
        "frames": 8,
        "fps": 6
      },
      "attack": {
        "row": 1,
        "frames": 6,
        "fps": 9
      },
      "hurt": {
        "row": 2,
        "frames": 5,
        "fps": 9
      }
    }
  },
  "boss_blade_crab": {
    "id": "boss_blade_crab",
    "url": "/art/anims/boss_blade_crab.png?v=f0fb163b",
    "frameW": 149,
    "frameH": 128,
    "feetY": 0.961,
    "facing": "right",
    "scale": 2.5,
    "clips": {
      "idle": {
        "row": 0,
        "frames": 8,
        "fps": 7
      },
      "attack": {
        "row": 1,
        "frames": 8,
        "fps": 11
      },
      "hurt": {
        "row": 2,
        "frames": 4,
        "fps": 9
      }
    }
  },
  "boss_flame_bull": {
    "id": "boss_flame_bull",
    "url": "/art/anims/boss_flame_bull.png?v=bca8c7ff",
    "frameW": 195,
    "frameH": 143,
    "feetY": 0.993,
    "facing": "right",
    "scale": 2.4,
    "clips": {
      "idle": {
        "row": 0,
        "frames": 8,
        "fps": 7
      },
      "attack": {
        "row": 1,
        "frames": 7,
        "fps": 11
      },
      "hurt": {
        "row": 2,
        "frames": 4,
        "fps": 8
      }
    }
  },
  "t5_nameless_sword_hermit": {
    "id": "t5_nameless_sword_hermit",
    "url": "/art/anims/t5_nameless_sword_hermit.png?v=a775788c",
    "frameW": 132,
    "frameH": 111,
    "feetY": 0.991,
    "facing": "right",
    "scale": 1.08,
    "clips": {
      "idle": {
        "row": 0,
        "frames": 8,
        "fps": 6
      },
      "attack": {
        "row": 1,
        "frames": 8,
        "fps": 12
      },
      "hurt": {
        "row": 2,
        "frames": 4,
        "fps": 9
      }
    }
  },
  "t5_blood_blade_lord": {
    "id": "t5_blood_blade_lord",
    "url": "/art/anims/t5_blood_blade_lord.png?v=c4ba5e83",
    "frameW": 133,
    "frameH": 139,
    "feetY": 0.993,
    "facing": "right",
    "scale": 1.15,
    "clips": {
      "idle": {
        "row": 0,
        "frames": 8,
        "fps": 6
      },
      "attack": {
        "row": 1,
        "frames": 8,
        "fps": 11
      },
      "hurt": {
        "row": 2,
        "frames": 4,
        "fps": 9
      }
    }
  },
  "t5_poison_matriarch": {
    "id": "t5_poison_matriarch",
    "url": "/art/anims/t5_poison_matriarch.png?v=e01d06d3",
    "frameW": 119,
    "frameH": 126,
    "feetY": 0.992,
    "facing": "right",
    "scale": 1.05,
    "clips": {
      "idle": {
        "row": 0,
        "frames": 8,
        "fps": 6
      },
      "attack": {
        "row": 1,
        "frames": 8,
        "fps": 10
      },
      "hurt": {
        "row": 2,
        "frames": 4,
        "fps": 9
      }
    }
  },
  "t5_iron_monk": {
    "id": "t5_iron_monk",
    "url": "/art/anims/t5_iron_monk.png?v=3e3ac943",
    "frameW": 124,
    "frameH": 112,
    "feetY": 0.991,
    "facing": "right",
    "scale": 1.2,
    "clips": {
      "idle": {
        "row": 0,
        "frames": 8,
        "fps": 6
      },
      "attack": {
        "row": 1,
        "frames": 8,
        "fps": 11
      },
      "hurt": {
        "row": 2,
        "frames": 4,
        "fps": 9
      }
    }
  },
  "t5_white_tiger": {
    "id": "t5_white_tiger",
    "url": "/art/anims/t5_white_tiger.png?v=a52da2fb",
    "frameW": 170,
    "frameH": 114,
    "feetY": 0.991,
    "facing": "right",
    "scale": 1.3,
    "clips": {
      "idle": {
        "row": 0,
        "frames": 8,
        "fps": 7
      },
      "attack": {
        "row": 1,
        "frames": 8,
        "fps": 12
      },
      "hurt": {
        "row": 2,
        "frames": 4,
        "fps": 9
      }
    }
  },
  "t5_wolf_king": {
    "id": "t5_wolf_king",
    "url": "/art/anims/t5_wolf_king.png?v=967c4375",
    "frameW": 161,
    "frameH": 118,
    "feetY": 0.983,
    "facing": "right",
    "scale": 1.35,
    "clips": {
      "idle": {
        "row": 0,
        "frames": 8,
        "fps": 6
      },
      "attack": {
        "row": 1,
        "frames": 8,
        "fps": 12
      },
      "hurt": {
        "row": 2,
        "frames": 4,
        "fps": 9
      }
    }
  },
  "beast_wolf": {
    "id": "beast_wolf",
    "url": "/art/anims/beast_wolf.png?v=1ea88daa",
    "frameW": 130,
    "frameH": 100,
    "feetY": 0.94,
    "facing": "right",
    "scale": 0.78,
    "clips": {
      "idle": {
        "row": 0,
        "frames": 6,
        "fps": 6
      },
      "attack": {
        "row": 1,
        "frames": 8,
        "fps": 12
      },
      "hurt": {
        "row": 2,
        "frames": 6,
        "fps": 10
      }
    }
  }
};
