// Generated by scripts/build-anim-sheets.ts — do not edit by hand.
import type { AnimSheet } from "./anim-sheets";

export const ANIM_SHEET_DATA: Record<string, AnimSheet> = {
  "boss_golden_serpent": {
    "id": "boss_golden_serpent",
    "url": "/art/anims/boss_golden_serpent.png?v=0",
    "frameW": 160,
    "frameH": 160,
    "feetY": 0.92,
    "facing": "right",
    "scale": 2.2,
    "clips": {
      "idle": {
        "row": 0,
        "frames": 4,
        "fps": 6
      },
      "attack": {
        "row": 1,
        "frames": 4,
        "fps": 10
      },
      "hurt": {
        "row": 2,
        "frames": 4,
        "fps": 10
      }
    }
  },
  "boss_blood_tiger": {
    "id": "boss_blood_tiger",
    "url": "/art/anims/boss_blood_tiger.png?v=0",
    "frameW": 160,
    "frameH": 160,
    "feetY": 0.92,
    "facing": "right",
    "scale": 2.2,
    "clips": {
      "idle": {
        "row": 0,
        "frames": 4,
        "fps": 6
      },
      "attack": {
        "row": 1,
        "frames": 4,
        "fps": 10
      },
      "hurt": {
        "row": 2,
        "frames": 4,
        "fps": 10
      }
    }
  },
  "boss_sword_eagle": {
    "id": "boss_sword_eagle",
    "url": "/art/anims/boss_sword_eagle.png?v=0",
    "frameW": 160,
    "frameH": 160,
    "feetY": 0.92,
    "facing": "right",
    "scale": 2.2,
    "clips": {
      "idle": {
        "row": 0,
        "frames": 4,
        "fps": 6
      },
      "attack": {
        "row": 1,
        "frames": 4,
        "fps": 10
      },
      "hurt": {
        "row": 2,
        "frames": 4,
        "fps": 10
      }
    }
  },
  "boss_sun_turtle": {
    "id": "boss_sun_turtle",
    "url": "/art/anims/boss_sun_turtle.png?v=0",
    "frameW": 160,
    "frameH": 160,
    "feetY": 0.92,
    "facing": "right",
    "scale": 2.2,
    "clips": {
      "idle": {
        "row": 0,
        "frames": 4,
        "fps": 6
      },
      "attack": {
        "row": 1,
        "frames": 4,
        "fps": 10
      },
      "hurt": {
        "row": 2,
        "frames": 4,
        "fps": 10
      }
    }
  },
  "boss_blade_crab": {
    "id": "boss_blade_crab",
    "url": "/art/anims/boss_blade_crab.png?v=0",
    "frameW": 160,
    "frameH": 160,
    "feetY": 0.92,
    "facing": "right",
    "scale": 2.2,
    "clips": {
      "idle": {
        "row": 0,
        "frames": 4,
        "fps": 6
      },
      "attack": {
        "row": 1,
        "frames": 4,
        "fps": 10
      },
      "hurt": {
        "row": 2,
        "frames": 4,
        "fps": 10
      }
    }
  },
  "boss_flame_bull": {
    "id": "boss_flame_bull",
    "url": "/art/anims/boss_flame_bull.png?v=0",
    "frameW": 160,
    "frameH": 160,
    "feetY": 0.92,
    "facing": "right",
    "scale": 2.2,
    "clips": {
      "idle": {
        "row": 0,
        "frames": 4,
        "fps": 6
      },
      "attack": {
        "row": 1,
        "frames": 4,
        "fps": 10
      },
      "hurt": {
        "row": 2,
        "frames": 4,
        "fps": 10
      }
    }
  },
  "t5_nameless_sword_hermit": {
    "id": "t5_nameless_sword_hermit",
    "url": "/art/anims/t5_nameless_sword_hermit.png?v=0",
    "frameW": 160,
    "frameH": 160,
    "feetY": 0.92,
    "facing": "right",
    "scale": 1.1,
    "clips": {
      "idle": {
        "row": 0,
        "frames": 4,
        "fps": 6
      },
      "attack": {
        "row": 1,
        "frames": 4,
        "fps": 10
      },
      "hurt": {
        "row": 2,
        "frames": 4,
        "fps": 10
      }
    }
  },
  "t5_blood_blade_lord": {
    "id": "t5_blood_blade_lord",
    "url": "/art/anims/t5_blood_blade_lord.png?v=0",
    "frameW": 160,
    "frameH": 160,
    "feetY": 0.92,
    "facing": "right",
    "scale": 1.1,
    "clips": {
      "idle": {
        "row": 0,
        "frames": 4,
        "fps": 6
      },
      "attack": {
        "row": 1,
        "frames": 4,
        "fps": 10
      },
      "hurt": {
        "row": 2,
        "frames": 4,
        "fps": 10
      }
    }
  },
  "t5_poison_matriarch": {
    "id": "t5_poison_matriarch",
    "url": "/art/anims/t5_poison_matriarch.png?v=0",
    "frameW": 160,
    "frameH": 160,
    "feetY": 0.92,
    "facing": "right",
    "scale": 1.1,
    "clips": {
      "idle": {
        "row": 0,
        "frames": 4,
        "fps": 6
      },
      "attack": {
        "row": 1,
        "frames": 4,
        "fps": 10
      },
      "hurt": {
        "row": 2,
        "frames": 4,
        "fps": 10
      }
    }
  },
  "t5_iron_monk": {
    "id": "t5_iron_monk",
    "url": "/art/anims/t5_iron_monk.png?v=0",
    "frameW": 160,
    "frameH": 160,
    "feetY": 0.92,
    "facing": "right",
    "scale": 1.1,
    "clips": {
      "idle": {
        "row": 0,
        "frames": 4,
        "fps": 6
      },
      "attack": {
        "row": 1,
        "frames": 4,
        "fps": 10
      },
      "hurt": {
        "row": 2,
        "frames": 4,
        "fps": 10
      }
    }
  },
  "t5_white_tiger": {
    "id": "t5_white_tiger",
    "url": "/art/anims/t5_white_tiger.png?v=0",
    "frameW": 160,
    "frameH": 160,
    "feetY": 0.92,
    "facing": "right",
    "scale": 1.1,
    "clips": {
      "idle": {
        "row": 0,
        "frames": 4,
        "fps": 6
      },
      "attack": {
        "row": 1,
        "frames": 4,
        "fps": 10
      },
      "hurt": {
        "row": 2,
        "frames": 4,
        "fps": 10
      }
    }
  },
  "t5_wolf_king": {
    "id": "t5_wolf_king",
    "url": "/art/anims/t5_wolf_king.png?v=0",
    "frameW": 160,
    "frameH": 160,
    "feetY": 0.92,
    "facing": "right",
    "scale": 1.1,
    "clips": {
      "idle": {
        "row": 0,
        "frames": 4,
        "fps": 6
      },
      "attack": {
        "row": 1,
        "frames": 4,
        "fps": 10
      },
      "hurt": {
        "row": 2,
        "frames": 4,
        "fps": 10
      }
    }
  }
};
