// Generated by scripts/build-pixellab-sheets.ts — do not edit by hand.
import type { PlSheet } from "./pl-sheets";

export const PL_SHEET_DATA: Record<string, PlSheet> = {
  "f1": {
    "id": "f1",
    "url": "/art/characters/pl/f1.png?v=4b48b794",
    "cell": 148,
    "columns": 8,
    "rows": 13,
    "feetY": 136,
    "figure": 121,
    "clips": {
      "idle": {
        "frames": [45, 46, 47, 48],
        "fps": 5,
        "repeat": -1
      },
      "walk": {
        "frames": [21, 22, 23, 24, 25, 26, 27, 28],
        "fps": 10,
        "repeat": -1
      },
      "walkNorth": {
        "frames": [37, 38, 39, 40, 41, 42, 43, 44],
        "fps": 10,
        "repeat": -1
      },
      "walkSouth": {
        "frames": [5, 6, 7, 8, 9, 10, 11, 12],
        "fps": 10,
        "repeat": -1
      },
      "attack": {
        "frames": [53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64],
        "fps": 12,
        "repeat": 0
      },
      "hurt": {
        "frames": [65, 66, 67, 68, 69, 70, 71],
        "fps": 10,
        "repeat": 0
      },
      "guard": {
        "frames": [72, 73, 74, 75, 76, 77, 78, 79, 80],
        "fps": 8,
        "repeat": -1
      },
      "victory": {
        "frames": [81, 82, 83, 84, 85, 86, 87, 88, 89],
        "fps": 8,
        "repeat": 0
      },
      "defeat": {
        "frames": [90, 91, 92, 93, 94, 95, 96, 97, 98],
        "fps": 8,
        "repeat": 0
      }
    },
    "battleIdle": {
      "frames": [49, 50, 51, 52],
      "fps": 5,
      "repeat": -1
    },
    "walk8": {
      "walk": {
        "S": [5, 6, 7, 8, 9, 10, 11, 12],
        "SE": [13, 14, 15, 16, 17, 18, 19, 20],
        "E": [21, 22, 23, 24, 25, 26, 27, 28],
        "NE": [29, 30, 31, 32, 33, 34, 35, 36],
        "N": [37, 38, 39, 40, 41, 42, 43, 44]
      },
      "stand": {
        "S": 0,
        "SE": 1,
        "E": 2,
        "NE": 3,
        "N": 4
      },
      "fps": 10
    }
  },
  "m1": {
    "id": "m1",
    "url": "/art/characters/pl/m1.png?v=ff841d3a",
    "cell": 146,
    "columns": 8,
    "rows": 13,
    "feetY": 136,
    "figure": 120,
    "clips": {
      "idle": {
        "frames": [45, 46, 47, 48],
        "fps": 5,
        "repeat": -1
      },
      "walk": {
        "frames": [21, 22, 23, 24, 25, 26, 27, 28],
        "fps": 10,
        "repeat": -1
      },
      "walkNorth": {
        "frames": [37, 38, 39, 40, 41, 42, 43, 44],
        "fps": 10,
        "repeat": -1
      },
      "walkSouth": {
        "frames": [5, 6, 7, 8, 9, 10, 11, 12],
        "fps": 10,
        "repeat": -1
      },
      "attack": {
        "frames": [53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64],
        "fps": 12,
        "repeat": 0
      },
      "hurt": {
        "frames": [65, 66, 67, 68, 69, 70, 71],
        "fps": 10,
        "repeat": 0
      },
      "guard": {
        "frames": [72, 73, 74, 75, 76, 77, 78, 79, 80],
        "fps": 8,
        "repeat": -1
      },
      "victory": {
        "frames": [81, 82, 83, 84, 85, 86, 87, 88, 89],
        "fps": 8,
        "repeat": 0
      },
      "defeat": {
        "frames": [90, 91, 92, 93, 94, 95, 96, 97, 98],
        "fps": 8,
        "repeat": 0
      }
    },
    "battleIdle": {
      "frames": [49, 50, 51, 52],
      "fps": 5,
      "repeat": -1
    },
    "walk8": {
      "walk": {
        "S": [5, 6, 7, 8, 9, 10, 11, 12],
        "SE": [13, 14, 15, 16, 17, 18, 19, 20],
        "E": [21, 22, 23, 24, 25, 26, 27, 28],
        "NE": [29, 30, 31, 32, 33, 34, 35, 36],
        "N": [37, 38, 39, 40, 41, 42, 43, 44]
      },
      "stand": {
        "S": 0,
        "SE": 1,
        "E": 2,
        "NE": 3,
        "N": 4
      },
      "fps": 10
    }
  }
};
