/**
 * The 20 sects' signature sets (16 assets each) for build-asset-plan.ts.
 * Six shared slots (gate, banner, dummy, weapon rack, altar, lantern) take the
 * sect's look; ten items are the sect's own. Data only; see docs/assets.md.
 */
import type { ArtRegion, AssetKind } from "./plan-content";

export interface SectArt {
  /** SectId where the game has one (lib/world/types.ts), else the location suffix. */
  id: string;
  thai: string;
  /** English name for prompts. */
  thaiEn?: string;
  region: ArtRegion;
  /** Colours and materials. */
  look: string;
  weapon: string;
  emblem: string;
  /** [key, Thai, English subject, subcategory, kind, mapWidth, size px] */
  items: [string, string, string, string, AssetKind, number, number][];
}

export const SECT_SLOTS: [string, string, (s: SectArt) => string, string, AssetKind, number, number][] = [
  ["gate", "ประตูสำนัก", (s) => `the mountain gate archway of the ${s.thaiEn ?? s.id} sect, ${s.look}`, "gate", "building", 200, 128],
  ["banner", "ธงสำนัก", (s) => `a tall sect war banner on a pole showing ${s.emblem}, ${s.look}`, "banner", "tall", 40, 64],
  ["dummy", "หุ่นฝึก", (s) => `a martial arts training dummy of the sect, ${s.look}`, "training", "tall", 35, 64],
  ["weapon_rack", "ชั้นวางอาวุธ", (s) => `a weapon rack holding ${s.weapon}, ${s.look}`, "weapon", "solid", 55, 64],
  ["altar", "แท่นบูชา", (s) => `the sect's altar table with offerings and ${s.emblem}, ${s.look}`, "religious", "solid", 60, 64],
  ["lantern", "โคมสำนัก", (s) => `a standing lantern of the sect, ${s.look}`, "lantern", "tall", 25, 64],
];

export const SECTS: SectArt[] = [
  { id: "shaolin", thai: "เส้าหลิน", thaiEn: "Shaolin", region: "heartland", look: "Buddhist monastery, saffron and brown, bronze and old timber", weapon: "wooden staffs and monk spades", emblem: "a golden dharma wheel",
    items: [
      ["arhat_statue", "รูปปั้นอรหันต์", "a stone statue of a fierce arhat in a fighting pose", "statue", "tall", 45, 96],
      ["buddha_statue", "พระพุทธรูป", "a seated golden Buddha statue on a lotus throne", "statue", "solid", 55, 96],
      ["wooden_man", "หุ่นไม้มู่หยินจวง", "a wooden-man training dummy with arms on a frame", "training", "solid", 40, 64],
      ["temple_bell", "ระฆังวัด", "a big bronze temple bell hanging in a wooden frame", "bell", "solid", 55, 64],
      ["stone_stele", "ศิลาจารึก", "a tall stone stele on a tortoise base (carvings, no readable text)", "stele", "tall", 40, 64],
      ["incense_cauldron", "กระถางธูปทองเหลือง", "a giant bronze incense cauldron on three legs with smoke", "religious", "solid", 50, 64],
      ["prayer_cushions", "เบาะนั่งสมาธิ", "a row of round straw meditation cushions", "seat", "flat", 50, 64],
      ["sutra_case", "ตู้พระสูตร", "a lacquered sutra case with scroll compartments", "storage", "solid", 45, 64],
      ["plum_posts", "เสาดอกเหมย", "plum-blossom training posts of different heights for stance practice", "training", "solid", 70, 64],
      ["wooden_fish", "โมกขระ", "a large wooden fish drum (muyu) on a stand", "instrument", "solid", 35, 64],
    ] },
  { id: "wudang", thai: "อู่ตัง", thaiEn: "Wudang", region: "north", look: "Taoist, blue-grey and white, dark green glazed tiles", weapon: "straight Taoist jian swords and horsetail whisks", emblem: "a black-and-white taiji yin-yang symbol",
    items: [
      ["zhenwu_statue", "รูปปั้นเจินอู่", "a statue of the Taoist god Zhenwu with a sword, standing on a turtle and snake", "statue", "tall", 50, 96],
      ["taiji_platform", "ลานไทจี๋", "a round stone platform inlaid with a taiji yin-yang symbol", "platform", "flat", 90, 96],
      ["bagua_mirror", "กระจกแปดทิศ", "an octagonal bagua mirror stand", "religious", "tall", 30, 64],
      ["alchemy_furnace", "เตาหลอมยาอายุวัฒนะ", "a bronze Taoist alchemy furnace with smoke", "craft", "solid", 45, 64],
      ["crane_statue", "รูปปั้นกระเรียน", "a bronze crane statue on one leg", "statue", "tall", 30, 64],
      ["sword_stand", "แท่นปักกระบี่", "a stone stand with a single sword stuck in it", "weapon", "solid", 30, 64],
      ["incense_tripod", "กระถางธูปสามขา", "a bronze Taoist tripod incense burner", "religious", "solid", 40, 64],
      ["talisman_post", "เสายันต์", "a wooden post covered with yellow paper talismans", "religious", "tall", 25, 64],
      ["tea_pavilion", "ศาลาเต๋า", "a small Taoist hexagonal pavilion with dark green tiles", "pavilion", "building", 110, 96],
      ["turtle_snake", "รูปปั้นเต่าพันงู", "a bronze statue of a turtle entwined with a snake", "statue", "solid", 40, 64],
    ] },
  { id: "emei", thai: "ง้อไบ๊", thaiEn: "Emei", region: "south", look: "Buddhist nunnery, white, pale jade green and soft gold", weapon: "slender swords and emei piercers", emblem: "a white lotus",
    items: [
      ["samantabhadra", "รูปปั้นโพธิสัตว์บนช้างขาว", "a statue of the bodhisattva Samantabhadra riding a white six-tusked elephant", "statue", "solid", 60, 96],
      ["lotus_pond", "สระบัวขาว", "a small stone pond with white lotus flowers", "water", "flat", 70, 64],
      ["golden_stupa", "สถูปทองยอดเขา", "a small golden summit stupa", "religious", "tall", 40, 96],
      ["bell_frame", "ระฆังสำริดเล็ก", "a small bronze bell under a little roof", "bell", "solid", 35, 64],
      ["sword_pond_stand", "แท่นวางกระบี่หยก", "a jade-green sword on a carved wooden stand", "weapon", "solid", 30, 64],
      ["prayer_beads_altar", "แท่นลูกประคำ", "a low altar with long prayer beads and a lotus lamp", "religious", "solid", 40, 64],
      ["monkey_statue", "รูปปั้นลิงเอ๋อเหมย", "a stone statue of an Emei macaque monkey", "statue", "solid", 25, 64],
      ["herb_table", "โต๊ะปรุงยา", "a nun's herb-preparation table with bowls and a mortar", "craft", "solid", 50, 64],
      ["cloud_lamp", "ตะเกียงเมฆ", "a white stone lantern carved with clouds", "lantern", "tall", 25, 64],
      ["meditation_rock", "หินนั่งสมาธิ", "a flat meditation rock with a white cushion", "rock", "solid", 40, 64],
    ] },
  { id: "huashan", thai: "หัวซาน", thaiEn: "Huashan", region: "west", look: "sword sect, blue and white robes, granite cliffs and old pines", weapon: "long straight swords", emblem: "a sword crossing a mountain peak",
    items: [
      ["sword_monument", "อนุสาวรีย์กระบี่", "a granite monument carved like a giant upright sword", "statue", "tall", 40, 96],
      ["cliff_pine", "สนหน้าผา", "a gnarled pine growing from a cliff ledge", "tree", "tree", 80, 96],
      ["plank_walk", "ทางเดินไม้ริมผา", "a short section of plank walkway bolted to a cliff with chains", "path", "solid", 90, 96],
      ["sword_rack_tall", "ชั้นวางกระบี่ยาว", "a tall rack of many long swords", "weapon", "solid", 50, 64],
      ["chess_pavilion", "ศาลาหมากล้อม", "a cliff-top stone table with a go board", "table", "solid", 45, 64],
      ["iron_chain_post", "เสาโซ่เหล็ก", "an iron post with heavy chains for climbing", "path", "tall", 25, 64],
      ["sword_grinding", "หินลับกระบี่", "a sword-sharpening stone with water trough", "craft", "solid", 40, 64],
      ["ancestor_tablet", "ป้ายวิญญาณบรรพจารย์", "an ancestral tablet shrine of the sword masters", "religious", "solid", 40, 64],
      ["training_target", "เป้าฝึกกระบี่", "a sword practice target of straw bundles on a post", "training", "tall", 30, 64],
      ["stone_steps", "บันไดหินผา", "a short flight of steep stone steps cut into rock", "path", "solid", 60, 64],
    ] },
  { id: "hengshan_south", thai: "เฮิงซาน", thaiEn: "Southern Hengshan", region: "south", look: "russet and autumn gold, red maples and dark wood", weapon: "swords and huqin fiddles with hidden blades", emblem: "five peaks above clouds",
    items: [
      ["huqin_stand", "ซอหูฉินซ่อนกระบี่", "a huqin two-string fiddle on a stand with a hidden blade", "instrument", "solid", 25, 64],
      ["maple_shrine", "ศาลเล็กใต้เมเปิล", "a tiny wayside shrine under red maple leaves", "religious", "solid", 40, 64],
      ["five_peak_rock", "หินห้ายอด", "a decorative rock with five little peaks on a base", "decor", "solid", 40, 64],
      ["music_pavilion", "ศาลาดนตรี", "a small open music pavilion with russet pillars", "pavilion", "building", 110, 96],
      ["incense_coil", "ธูปขด", "hanging spiral incense coils under a frame", "religious", "overhead", 35, 64],
      ["fire_altar", "แท่นไฟเฮิงซาน", "a stone fire altar of the southern sacred mountain", "religious", "solid", 40, 64],
      ["sword_case", "หีบกระบี่", "a long lacquered sword case on trestles", "weapon", "solid", 45, 64],
      ["red_maple", "เมเปิลแดง", "a small red maple tree", "tree", "tree", 70, 64],
      ["drum_stand", "กลองศึก", "a red war drum on a wooden stand", "instrument", "solid", 40, 64],
      ["tea_stove", "เตาชาภูเขา", "a mountain tea stove with a kettle", "kitchen", "solid", 30, 64],
    ] },
  { id: "hengshan_north", thai: "เหิงซาน", thaiEn: "Northern Hengshan", region: "north", look: "Buddhist nuns, grey and white, cliff-hanging temple timber", weapon: "swords hidden in flutes and short swords", emblem: "a white crescent over a peak",
    items: [
      ["hanging_temple", "วัดแขวนผา", "a small hanging temple pavilion on wooden stilts against a cliff", "temple", "building", 130, 96],
      ["flute_rack", "ชั้นวางขลุ่ยซ่อนดาบ", "a rack of bamboo flutes that hide blades", "weapon", "solid", 40, 64],
      ["guanyin_statue", "รูปปั้นกวนอิม", "a white stone Guanyin statue", "statue", "tall", 35, 96],
      ["prayer_flags_line", "ธงคำอธิษฐานเทา", "a line of grey and white prayer pennants on poles", "banner", "overhead", 70, 64],
      ["stone_lamp", "ตะเกียงหินภูเขา", "a mountain stone lamp", "lantern", "tall", 25, 64],
      ["nun_hut", "กุฏิชี", "a tiny one-room nun's hermitage of grey stone", "house", "building", 90, 96],
      ["sutra_table", "โต๊ะสวดมนต์", "a low sutra-chanting table with an open scroll and a bell", "religious", "solid", 40, 64],
      ["pine_bonsai", "บอนไซสน", "a pine bonsai in a stone tray", "plant", "solid", 25, 64],
      ["wind_chimes", "กระดิ่งลม", "bronze wind chimes hanging from an eave corner", "decor", "overhead", 20, 64],
      ["snow_stone", "ศิลาหิมะ", "a smooth snow-dusted standing stone", "rock", "solid", 35, 64],
    ] },
  { id: "songshan", thai: "ซงซาน", thaiEn: "Songshan", region: "heartland", look: "dark green and iron grey, austere stone and heavy timber", weapon: "heavy broad swords", emblem: "the five-mountain alliance flag",
    items: [
      ["alliance_flag", "ธงพันธมิตรห้าขุนเขา", "a huge alliance flag on a stone base, dark green with five peaks", "banner", "tall", 45, 96],
      ["heavy_sword_rack", "ชั้นวางดาบหนัก", "a rack of heavy iron broadswords", "weapon", "solid", 55, 64],
      ["stone_weights", "ลูกตุ้มหินฝึกกำลัง", "stone lifting weights and padlock-shaped stones", "training", "solid", 40, 64],
      ["iron_tripod", "กระถางเหล็กสามขา", "an iron ritual tripod cauldron", "religious", "solid", 40, 64],
      ["council_table", "โต๊ะประชุมพันธมิตร", "a long council table with five chairs", "table", "solid", 90, 96],
      ["pillar_rock", "เสาหินขุนเขา", "a rugged stone pillar used for sword practice", "training", "tall", 35, 64],
      ["war_drum", "กลองรบ", "a big iron-banded war drum", "instrument", "solid", 40, 64],
      ["throne_chair", "เก้าอี้เจ้าสำนัก", "a carved stone sect leader's seat", "chair", "solid", 40, 64],
      ["torch_stand", "เสาคบเพลิง", "an iron torch stand with fire", "light", "tall", 20, 64],
      ["stone_tablet_wall", "กำแพงป้ายหิน", "a short stone wall with carved panels (no readable text)", "wall", "solid", 80, 64],
    ] },
  { id: "taishan", thai: "ไท่ซาน", thaiEn: "Taishan", region: "heartland", look: "imperial Taoist, ochre yellow and red, granite steps and old pines", weapon: "straight swords and long-handled sabres", emblem: "a rising sun over the eastern peak",
    items: [
      ["sacrifice_altar", "แท่นบวงสรวงฟ้า", "an imperial stone sacrificial altar with steps", "religious", "solid", 80, 96],
      ["stele_tortoise", "ศิลาจารึกบนเต่า", "a huge stele on a stone tortoise (no readable text)", "stele", "tall", 45, 96],
      ["sun_gate", "ประตูฟ้าใต้", "a stone archway gate on mountain steps", "gate", "building", 120, 96],
      ["incense_pavilion", "หอธูป", "a small yellow-roofed incense pavilion", "pavilion", "building", 90, 96],
      ["welcome_pine", "สนต้อนรับ", "an ancient welcoming pine with outstretched branch", "tree", "tree", 90, 96],
      ["stone_steps", "บันไดเจ็ดพันขั้น", "a short flight of granite mountain steps", "path", "solid", 60, 64],
      ["prayer_locks", "โซ่กุญแจอธิษฐาน", "an iron chain railing hung with red prayer locks", "decor", "solid", 60, 64],
      ["bronze_ding", "กระถางติ่ง", "a square bronze ding cauldron", "religious", "solid", 40, 64],
      ["sunrise_rock", "หินชมอรุณ", "a flat lookout rock for watching sunrise", "rock", "solid", 50, 64],
      ["red_lanterns", "โคมแดงคู่", "a pair of red lanterns on a wooden frame", "lantern", "tall", 35, 64],
    ] },
  { id: "quanzhen", thai: "ฉวนเจิน", thaiEn: "Quanzhen", region: "north", look: "Taoist, white robes with blue trim, grey stone and pine", weapon: "Taoist swords", emblem: "the seven stars of the Big Dipper",
    items: [
      ["dipper_formation", "ลานค่ายกลเจ็ดดาว", "a stone floor marked with seven star circles of the Big Dipper formation", "platform", "flat", 100, 96],
      ["chongyang_statue", "รูปปั้นปรมาจารย์หวังฉงหยาง", "a statue of an old Taoist founder holding a whisk", "statue", "tall", 40, 96],
      ["incense_ding", "กระถางธูปเต๋า", "a white-stone Taoist incense burner", "religious", "solid", 40, 64],
      ["scripture_rack", "ชั้นคัมภีร์เต๋า", "a rack of Taoist scripture scrolls", "storage", "solid", 45, 64],
      ["star_lamp", "ตะเกียงเจ็ดดาว", "a seven-armed star lamp stand", "light", "tall", 30, 64],
      ["pine_crane", "สนกับนกกระเรียน", "a pine tree with a white crane perched", "tree", "tree", 80, 96],
      ["meditation_cave", "ถ้ำบำเพ็ญ", "a small meditation cave entrance with a stone door", "cave", "building", 80, 96],
      ["sword_formation", "แท่นกระบี่เจ็ดเล่ม", "seven swords planted in a circle", "weapon", "solid", 50, 64],
      ["gourd_stand", "น้ำเต้ายาวิเศษ", "a stand with Taoist elixir gourds", "craft", "solid", 30, 64],
      ["bell_drum_pair", "ระฆังและกลองเต๋า", "a small bell and a drum on a shared stand", "instrument", "solid", 45, 64],
    ] },
  { id: "gumu", thai: "กู่มู่", thaiEn: "Ancient Tomb", region: "north", look: "underground tomb, cold white jade, grey stone, candlelight", weapon: "jade swords and white silk ribbons", emblem: "a jade disc",
    items: [
      ["jade_bed", "เตียงหยกเย็น", "a cold white jade bed glowing faintly", "bed", "solid", 70, 64],
      ["tomb_door", "ประตูสุสานหิน", "a massive stone tomb door with carvings", "gate", "building", 100, 96],
      ["stone_coffin", "โลงหิน", "a carved stone sarcophagus", "tomb", "solid", 60, 64],
      ["bee_hive", "รังผึ้งหยก", "a hive of jade-white bees in an earthen jar", "creature", "solid", 30, 64],
      ["candle_cluster", "เทียนในสุสาน", "a cluster of white candles on a stone ledge", "light", "solid", 30, 64],
      ["silk_rope", "เชือกไหมขาว", "a white silk rope strung between two posts for sleeping", "training", "solid", 60, 64],
      ["tomb_statue", "รูปปั้นผู้พิทักษ์สุสาน", "a stone tomb guardian statue", "statue", "tall", 35, 96],
      ["jade_screen", "ฉากหยก", "a carved white jade screen", "decor", "solid", 50, 64],
      ["bone_niche", "ช่องอัฐิ", "a stone wall niche with ancestral urns", "tomb", "solid", 45, 64],
      ["spring_pool", "บ่อน้ำพุเย็น", "a small icy underground spring pool", "water", "flat", 60, 64],
    ] },
  { id: "lingjiu", thai: "ลิ่งจิ้วกง", thaiEn: "Lingjiu Palace", region: "west", look: "Tianshan snow palace, white and lavender, ice and pale stone", weapon: "plum-blossom darts, short swords and silk sashes", emblem: "a spirit vulture with spread wings",
    items: [
      ["vulture_statue", "รูปปั้นแร้งวิญญาณ", "a white stone statue of a vulture with spread wings", "statue", "tall", 50, 96],
      ["ice_throne", "บัลลังก์น้ำแข็ง", "an ice-carved throne", "chair", "solid", 45, 64],
      ["snow_lotus_bed", "แปลงบัวหิมะ", "a bed of snow lotus flowers in snow", "plant", "flat", 50, 64],
      ["ice_pillar", "เสาน้ำแข็ง", "a translucent ice pillar", "decor", "tall", 25, 64],
      ["silk_curtain", "ม่านไหมม่วง", "lavender silk curtains on a stand", "decor", "solid", 50, 64],
      ["dart_rack", "ชั้นวางเข็มเหมย", "a rack of plum-blossom darts and needles", "weapon", "solid", 35, 64],
      ["frost_brazier", "เตาไฟน้ำแข็ง", "a brazier burning with pale blue fire", "light", "solid", 30, 64],
      ["crystal_cluster", "ผลึกหิมะ", "a big cluster of snow crystals", "crystal", "solid", 40, 64],
      ["fur_rug", "พรมขนสัตว์ขาว", "a white fur rug", "rug", "flat", 60, 64],
      ["palace_lantern", "โคมวังหิมะ", "a hexagonal white palace lantern", "lantern", "tall", 25, 64],
    ] },
  { id: "beggars", thai: "พรรคยาจก", thaiEn: "Beggars' Gang", region: "heartland", look: "ragged and patched, straw, bamboo and old cloth", weapon: "green bamboo dog-beating staffs", emblem: "a bowl and a bamboo staff",
    items: [
      ["dog_staff", "ไม้เท้าตีสุนัข", "a jade-green bamboo staff on a simple stand", "weapon", "solid", 25, 64],
      ["wine_gourds", "น้ำเต้าเหล้า", "a pile of wine gourds", "container", "solid", 30, 64],
      ["straw_shelter", "เพิงฟาง", "a ramshackle straw lean-to shelter", "house", "building", 90, 96],
      ["begging_bowls", "ชามขอทาน", "chipped begging bowls on a mat", "container", "flat", 30, 64],
      ["cooking_pot", "หม้อต้มริมทาง", "a big iron pot over a campfire", "kitchen", "solid", 40, 64],
      ["rag_banner", "ธงผ้าปะ", "a patched rag banner on a crooked pole", "banner", "tall", 35, 64],
      ["sack_pile", "กองย่าม", "a heap of patched cloth sacks", "container", "solid", 40, 64],
      ["straw_mats", "เสื่อฟาง", "rolled and spread straw sleeping mats", "seat", "flat", 50, 64],
      ["dog_bowl", "ชามข้าวสุนัข", "a stray dog curled by a bowl", "creature", "solid", 30, 64],
      ["broken_cart", "เกวียนพัง", "a broken old cart used as a shelter", "vehicle", "solid", 70, 64],
    ] },
  { id: "sunmoon", thai: "พรรคตะวันจันทรา", thaiEn: "Sun Moon Holy Cult", region: "east", look: "red and black lacquer, gold sun and silver moon motifs", weapon: "embroidery needles and black-lacquered swords", emblem: "a golden sun joined to a silver crescent moon",
    items: [
      ["sun_moon_altar", "แท่นตะวันจันทรา", "an altar with a golden sun and silver moon emblem", "religious", "solid", 55, 96],
      ["fire_bowl", "อ่างไฟศักดิ์สิทธิ์", "a large black iron bowl of holy fire", "light", "solid", 40, 64],
      ["black_throne", "บัลลังก์ดำ", "a black lacquered throne with red cushions", "chair", "solid", 50, 64],
      ["needle_case", "กล่องเข็มปัก", "an embroidery needle case and silk threads on a table", "weapon", "solid", 35, 64],
      ["red_banner_pair", "ธงแดงดำคู่", "a pair of red and black cult banners", "banner", "tall", 45, 64],
      ["blackwood_cliff_rail", "ราวผาไม้ดำ", "a black wooden cliff railing with a lantern", "fence", "solid", 70, 64],
      ["sun_statue", "รูปปั้นเทพตะวัน", "a statue of a radiant sun deity", "statue", "tall", 40, 96],
      ["moon_mirror", "กระจกจันทรา", "a round silver moon mirror on a stand", "decor", "tall", 30, 64],
      ["pill_cabinet", "ตู้ยาสามศพ", "a black cabinet of red cult pills", "storage", "solid", 40, 64],
      ["chain_brazier", "กระถางไฟโซ่", "a chained hanging fire brazier on a tripod", "light", "tall", 30, 64],
    ] },
  { id: "xiaoyao", thai: "พรรคสราญรมย์", thaiEn: "Xiaoyao", region: "north", look: "elegant and airy, white and pale blue, jade and silk", weapon: "jade flutes and fans", emblem: "a jade goddess",
    items: [
      ["go_board", "กระดานหมากล้อมเจินหลง", "a stone go board with an unfinished game", "table", "solid", 45, 64],
      ["jade_goddess", "รูปปั้นเทพธิดาหยก", "a jade statue of a graceful goddess", "statue", "tall", 35, 96],
      ["painting_easel", "ขาตั้งภาพวาด", "a painting easel with a portrait of a lady (no writing)", "decor", "solid", 35, 64],
      ["lake_pavilion", "ศาลากลางน้ำ", "a light pavilion over still water", "pavilion", "building", 110, 96],
      ["flute_table", "โต๊ะขลุ่ยหยก", "a low table with jade flutes", "instrument", "solid", 40, 64],
      ["silk_swing", "ชิงช้าไหม", "a silk swing hanging from a frame", "decor", "solid", 40, 64],
      ["wine_set", "ชุดสุราหยก", "a jade wine pot and cups on a tray", "table", "solid", 30, 64],
      ["star_chart", "แผนภูมิดาว", "a star chart scroll on a stand (no writing)", "decor", "solid", 35, 64],
      ["cloud_rock", "หินเมฆ", "a pale scholar's rock shaped like clouds", "decor", "solid", 35, 64],
      ["white_crane", "นกกระเรียนขาว", "a standing white crane", "creature", "tall", 25, 64],
    ] },
  { id: "xingxiu", thai: "สำนักดาวดึงส์", thaiEn: "Xingxiu", region: "west", look: "poison sect of the star sea, purple and black, desert stone", weapon: "poison needles and hooked staffs", emblem: "a star constellation over a sea",
    items: [
      ["poison_tripod", "กระถางพิษสามขา", "a dark poison tripod cauldron with green fumes", "craft", "solid", 45, 64],
      ["flattery_gong", "ฆ้องสรรเสริญ", "a big gong on a stand", "instrument", "solid", 40, 64],
      ["praise_banners", "ธงสรรเสริญ", "colourful praise banners on poles", "banner", "tall", 45, 64],
      ["insect_jars", "ไหแมลงพิษ", "clay jars of poisonous insects", "container", "solid", 35, 64],
      ["star_altar", "แท่นดวงดาว", "a purple star altar with a crystal", "religious", "solid", 45, 64],
      ["scorpion_cage", "กรงแมงป่อง", "a bamboo cage with scorpions", "creature", "solid", 30, 64],
      ["rotten_corpse_post", "เสาหุ่นพิษ", "a post with a poisoned straw dummy", "training", "tall", 30, 64],
      ["divan", "แท่นนั่งเจ้าสำนัก", "a luxurious purple divan for the sect master", "chair", "solid", 55, 64],
      ["star_pool", "บ่อดาว", "a dark pool with star reflections", "water", "flat", 60, 64],
      ["needle_rack", "ชั้นเข็มพิษ", "a rack of glinting poison needles", "weapon", "solid", 30, 64],
    ] },
  { id: "wudu", thai: "พรรคเบญจพิษ", thaiEn: "Five Poisons", region: "south", look: "Miao tribal, indigo and silver, bamboo and clay", weapon: "silver poison darts and curved knives", emblem: "the five poisons: centipede, snake, scorpion, toad and spider",
    items: [
      ["gu_jar", "ไหกู่", "a sealed black clay gu-poison jar with silver bands", "container", "solid", 30, 64],
      ["snake_altar", "แท่นบูชางู", "a bamboo altar with a coiled snake carving", "religious", "solid", 45, 64],
      ["toad_statue", "รูปปั้นคางคกทอง", "a golden toad statue", "statue", "solid", 30, 64],
      ["centipede_banner", "ธงตะขาบ", "an indigo banner with a centipede emblem", "banner", "tall", 35, 64],
      ["silver_drum", "กลองเงินเมี่ยว", "a Miao bronze drum with silver decoration", "instrument", "solid", 35, 64],
      ["poison_garden", "แปลงพืชพิษ", "a small bed of poisonous plants and mushrooms", "plant", "flat", 50, 64],
      ["spider_web_frame", "โครงใยแมงมุม", "a frame with a giant spider web", "decor", "solid", 40, 64],
      ["venom_rack", "ชั้นขวดพิษ", "a rack of venom bottles", "storage", "solid", 40, 64],
      ["bamboo_cages", "กรงสัตว์พิษ", "stacked bamboo cages with snakes and toads", "creature", "solid", 45, 64],
      ["incense_skull", "กระถางกะโหลก", "an incense burner made from an ox skull", "religious", "solid", 30, 64],
    ] },
  { id: "xuedao", thai: "พรรคอสูรโลหิต", thaiEn: "Blood Blade", region: "west", look: "evil Tibetan lama sect, maroon and blood red, bone and black iron", weapon: "blood-red curved sabres", emblem: "a crimson blade dripping blood",
    items: [
      ["blood_sabre_rack", "ชั้นดาบโลหิต", "a rack of blood-red curved sabres", "weapon", "solid", 45, 64],
      ["skull_pile", "กองกะโหลก", "a pile of skulls on a stone base", "bones", "solid", 35, 64],
      ["prayer_wheel_dark", "กงล้อดำ", "a dark prayer wheel with red cloth", "religious", "solid", 35, 64],
      ["bone_throne", "บัลลังก์กระดูก", "a throne of bones with a red pelt", "chair", "solid", 45, 64],
      ["blood_altar", "แท่นบูชาโลหิต", "a stone altar stained red with a bowl", "religious", "solid", 45, 64],
      ["dark_stupa", "สถูปดำ", "a small black stupa with red cloth", "religious", "tall", 35, 96],
      ["horn_trumpet", "แตรเขาสัตว์", "a long Tibetan horn on a stand", "instrument", "solid", 50, 64],
      ["torture_post", "เสาทรมาน", "a wooden post with chains", "training", "tall", 30, 64],
      ["red_flags", "ธงแดงโลหิต", "tattered blood-red prayer flags", "banner", "overhead", 60, 64],
      ["snow_tent", "กระโจมลามะแดง", "a maroon lama tent", "tent", "building", 90, 96],
    ] },
  { id: "xueyu", thai: "สำนักดาบโลหิต", thaiEn: "Blood Sword", region: "north", look: "new evil sword sect, crimson and black iron, dark stone", weapon: "crimson long swords", emblem: "a crimson sword through a black sun",
    items: [
      ["blood_pool", "สระเลือด", "a dark red pool in a stone basin", "water", "flat", 60, 64],
      ["crimson_sword_monument", "อนุสาวรีย์ดาบแดง", "a black iron monument with a crimson sword", "statue", "tall", 40, 96],
      ["iron_brazier", "เตาเหล็กดำ", "a black iron brazier with red flames", "light", "solid", 35, 64],
      ["chain_pillar", "เสาโซ่", "a black pillar wrapped in chains", "decor", "tall", 25, 64],
      ["oath_altar", "แท่นสาบานเลือด", "an altar with a blood oath bowl and dagger", "religious", "solid", 40, 64],
      ["armor_stand", "หุ่นเกราะดำ", "a black lacquered armour on a stand", "weapon", "solid", 35, 64],
      ["trial_ring", "ลานทดสอบ", "a small round fighting ring of black stones", "platform", "flat", 90, 96],
      ["crimson_banner", "ธงดาบแดง", "a crimson banner with a black sword", "banner", "tall", 40, 64],
      ["cage", "กรงเหล็ก", "an iron prisoner cage", "decor", "solid", 45, 64],
      ["skull_lamp", "ตะเกียงกะโหลก", "a lamp made from a skull on a pole", "light", "tall", 20, 64],
    ] },
  { id: "jinyiwei", thai: "องครักษ์เสื้อแพร", thaiEn: "Embroidered Uniform Guard", region: "heartland", look: "imperial secret police, red and gold brocade, black lacquer", weapon: "embroidered spring sabres (xiuchundao)", emblem: "a golden flying fish",
    items: [
      ["command_desk", "โต๊ะบัญชาการ", "a black lacquered command desk with tokens and seals", "table", "solid", 55, 64],
      ["sabre_rack", "ชั้นดาบซิ่วชุน", "a rack of slim embroidered spring sabres", "weapon", "solid", 45, 64],
      ["torture_rack", "แท่นสอบสวน", "an interrogation frame with chains and tools", "decor", "solid", 50, 64],
      ["prison_cell", "ห้องขังไม้", "a wooden prison cell cage", "decor", "solid", 60, 64],
      ["flying_fish_banner", "ธงปลาบิน", "a red banner with a golden flying fish", "banner", "tall", 40, 64],
      ["dossier_cabinet", "ตู้เอกสารลับ", "a cabinet full of secret dossiers", "storage", "solid", 45, 64],
      ["drum_of_grievance", "กลองร้องทุกข์", "a big petition drum on a frame", "instrument", "solid", 45, 64],
      ["imperial_lantern", "โคมวัง", "a red imperial palace lantern on a pole", "lantern", "tall", 25, 64],
      ["horse_post", "เสาผูกม้าองครักษ์", "a hitching post with a fine black horse saddle", "farm", "tall", 35, 64],
      ["arrow_target", "เป้าธนู", "an archery target on a stand", "training", "solid", 35, 64],
    ] },
  { id: "tang", thai: "สำนักสุลถัง", thaiEn: "Tang Clan", region: "south", look: "Sichuan clan of hidden weapons, dark green and black, bamboo and iron", weapon: "throwing knives, darts and repeating crossbows", emblem: "a black lotus of hidden blades",
    items: [
      ["crossbow_rack", "ชั้นหน้าไม้กล", "a rack of repeating crossbows", "weapon", "solid", 45, 64],
      ["dart_board", "เป้าอาวุธลับ", "a wooden target bristling with darts and knives", "training", "solid", 35, 64],
      ["mechanism_box", "หีบกลไก", "a mechanical trap box with gears", "craft", "solid", 35, 64],
      ["poison_workbench", "โต๊ะผสมพิษ", "a workbench with vials, scales and a mortar", "craft", "solid", 55, 64],
      ["iron_puppet", "หุ่นเหล็กกลไก", "a mechanical iron training puppet", "training", "tall", 35, 64],
      ["black_lotus_lamp", "ตะเกียงบัวดำ", "a black lotus-shaped lamp", "lantern", "tall", 25, 64],
      ["hidden_weapon_chest", "หีบอาวุธลับ", "an open chest of hidden weapons", "storage", "solid", 40, 64],
      ["bamboo_trap", "กับดักไผ่", "a sprung bamboo spike trap", "decor", "solid", 45, 64],
      ["tea_house_sichuan", "ร้านชาเสฉวน", "a small Sichuan bamboo teahouse booth", "shop", "building", 100, 96],
      ["clan_shrine", "ศาลบรรพชนตระกูลถัง", "a Tang clan ancestral shrine cabinet", "religious", "solid", 45, 64],
    ] },
];
