/**
 * Characters (one per NPC, prompt built from the NPC's tags, sect, gender and
 * age) and monsters (beasts, spirits, demons and foe archetypes) for
 * build-asset-plan.ts. See docs/assets.md.
 */
import type { NpcDef } from "@/lib/world/types";
import { npcCharacterId } from "@/lib/characters/catalog";

const SECT_DRESS: Record<string, string> = {
  shaolin: "a Shaolin monk with a shaved head in saffron and brown robes",
  wudang: "a Wudang Taoist in a blue-grey Taoist robe with a topknot and hairpin",
  emei: "an Emei Buddhist nun in a white and pale jade-green habit with a hood",
  huashan: "a Huashan swordsman in a blue and white robe with a long sword",
  songshan: "a Songshan swordsman in a dark green robe with a heavy broadsword",
  taishan: "a Taishan Taoist swordsman in an ochre-yellow robe",
  hengshan_south: "a Southern Hengshan swordsman in a russet robe",
  hengshan_north: "a Northern Hengshan Buddhist nun in a grey habit with a sword",
  quanzhen: "a Quanzhen Taoist in a white robe with blue trim and a topknot",
  gumu: "an Ancient Tomb sect fighter in pure white silk",
  lingjiu: "a Lingjiu Palace warrior in lavender and white with a fur collar",
  beggars: "a Beggars' Gang fighter in patched ragged clothes with a wine gourd and a bamboo staff",
  sunmoon: "a Sun Moon cult member in red and black robes with gold trim",
  ming_sect: "a Sun Moon cult member in red and black robes with gold trim",
  xiaoyao: "a Xiaoyao sect member in an elegant pale-blue silk robe",
  xingxiu: "a Xingxiu poison-sect disciple in a purple robe",
  wudu: "a Miao Five Poisons cultist in indigo clothes with silver jewellery",
  xuedao: "a Blood Blade lama in maroon robes with a blood-red curved sabre",
  xueyu: "a Blood Sword sect fighter in crimson and black",
  jinyiwei: "an imperial Embroidered Uniform Guard in a red-gold flying-fish robe, black gauze hat and slim sabre",
  tang: "a Tang clan hidden-weapon expert in dark green and black with dart pouches",
};

const ROLE_DRESS: [RegExp, string][] = [
  [/\bghost\b/, "the translucent pale-blue ghost of an ancient armoured warrior"],
  [/\beunuch\b/, "a palace eunuch in a dark official robe and hat"],
  [/\bmaid\b/, "a Chinese palace maid in a pale pink hanfu robe with her hair in two buns"],
  [/\bactor\b/, "a Chinese opera actor in a colourful costume"],
  [/\bpainter\b/, "a drunken painter with a brush and a wine gourd"],
  [/\bassassin\b/, "an assassin in black with a hood and twin daggers"],
  [/\bcult_leader\b/, "a cult leader in a dark robe with a dragon emblem"],
  [/\bheretic\b/, "a fallen monk in torn dark robes with prayer beads"],
  [/\bbandit\b|\boutlaw\b/, "a bandit chief with a broad sabre and leather armour"],
  [/\bvenom_master\b/, "a poison master in dark green with venom gourds"],
  [/\bspy\b|\binformant\b/, "a commoner in plain clothes (secretly a spy)"],
  [/\bofficial\b|\bauthority\b|\bnoble\b|\blord\b/, "an official in a dark silk robe with a black gauze hat"],
  [/\bmerchant\b|\bcollector\b/, "a merchant in a brown silk robe and cap"],
  [/\bhealer\b|\bherbalist\b|\bdoctor\b/, "a herbalist doctor with a medicine box"],
  [/\bchef\b|\bcook\b/, "a cook in an apron holding a ladle"],
  [/\bfisherman\b|\bfisher\b/, "a fisherman with a conical straw hat and a fishing rod"],
  [/\bfarmer\b|\bwoodcutter\b|\blaborer\b|\bporter\b/, "a labourer in plain hemp clothes with a carrying pole"],
  [/\bherder\b/, "a herder in a sheepskin coat with a crook"],
  [/\bhunter\b/, "a hunter with a bow and a fur vest"],
  [/\bmusician\b/, "a musician carrying a guqin zither"],
  [/\binnkeeper\b/, "an innkeeper with an apron and a towel over the shoulder"],
  [/\bblacksmith\b|\bforge\b|\bsmith\b|\bcraftsman\b/, "a craftsman with a leather apron and a hammer"],
  [/\bservant\b|\bgardener\b/, "a servant in plain grey clothes"],
  [/\bsoldier\b|\bguard\b|\bescort\b/, "a guard in lamellar armour with a spear"],
  [/\bscholar\b|\bdiviner\b|\bpoet\b|\bteacher\b|\bstrategist\b/, "a scholar in a pale robe holding a folding fan"],
  [/\bmonk\b/, "a Buddhist monk with a shaved head in a brown robe"],
  [/\bnun\b/, "a Buddhist nun in a grey habit"],
  [/\btaoist\b/, "a Taoist priest in a blue robe with a whisk"],
  [/\bhermit\b|\brecluse\b|\bexile\b|\bsage\b/, "a hermit master in a loose grey-green robe"],
  [/\bblade\b|\bblademaster\b/, "a sabre master with a broad dao"],
  [/swords(man|woman)|\bwarrior\b|\bfighter\b|\bmartial_artist\b|\bmaster\b|\bhero\b|\bsparring\b|\bwanderer\b|\badventurer\b/, "a wandering martial artist with a sword on the back"],
  [/\bchild\b/, "a small child in simple clothes"],
];

const OVERRIDES: Record<string, string> = {
  swordsman_xiao: "a lean wandering swordsman in a travel-worn grey robe and bamboo hat, sword at his hip",
  jail_elder_prisoner: "an old prisoner in a ragged grey prison tunic with a long unkempt beard",
  wld_taohua_hermit_huang: "the eccentric Peach Blossom Island master in a green scholar's robe with a jade flute",
  wld_motian_ghost_liang: "the translucent pale-blue ghost of an ancient armoured warrior with a broken spear",
  wld_jinshe_beasttamer_xu: "a young woman snake tamer in a dark green dress with a golden snake around her arm",
  wld_miao_tribaleldr_abao: "an old Miao tribal chief in indigo clothes with a big silver neck ring and a staff",
  wld_desert_collector_mo: "an old desert antique collector in a dusty robe and wide hat with a bag of relics",
  wld_kunlun_exile_qiu: "an exiled Kunlun elder in a frayed white robe with a long sword",
  tribe_huizu_wrestler_ma: "a broad-shouldered Hui tribal wrestler in a sleeveless vest and white cap",
  tribe_huizu_caravan_nasir: "a desert caravan leader with a turban, scarred face and curved sword",
  tribe_huizu_herder_aisha: "a small Hui herder girl with an orange headscarf and a crook",
  tribe_huizu_smith_hai: "an old Hui blacksmith with a white cap, leather apron and hammer",
  palace_royal_guard_zhao: "a young imperial palace guard in red-gold armour with a long spear",
  palace_royal_official_qian: "a pot-bellied court official in a red robe and black winged hat",
  home_hufei_master_hufei: "a fierce bearded sabre hero in a dark brown fur-trimmed robe with a dao",
  home_hufei_guest_yuan: "a mysterious young woman in a purple dress with a sword",
  home_hufei_guest_jiu: "a staggering old drunkard with a wine gourd and red nose",
  home_beichou_hermit_bei: "a hermit warrior with a burn-scarred face, a dark cloak and a long spear",
  home_miaoren_master_miao: "a tall stern frontier swordsman in a black robe with a long sword",
  home_miaoren_daughter_ruolan: "a gentle young woman in a pale blue dress holding a pipa lute",
  home_chengying_mistress_cheng: "a gentle young woman in a pale green dress with a jade flute",
  home_xuemuhua_doctor_xue: "a famous physician in a white robe with a medicine box",
  home_xuemuhua_guest_li: "a Peking-opera actor in a bright painted costume and headdress",
  villa_meizhuang_master_heibai: "a pale scholar with half-black half-white hair in a grey robe holding go stones",
  villa_meizhuang_painter_danqing: "a red-faced drunken painter in a stained robe with a brush and a wine gourd",
  villa_fuwei_young_lin: "a handsome young nobleman in fine white silk with a hunting bow",
  home_yideng_monk_yideng: "an old monk, a former emperor, in a plain brown robe with a gentle face",
  home_tianboguang_blade_tian: "a roguish swift blade-fighter in a black robe with a sabre",
  evil_shenlong_cult_leader_zhao: "a cult leader in a golden-black robe with a dragon emblem",
  evil_zhizhu_assassin_ying: "a shadow assassin in black with a mask and spider-silk claws",
  evil_chuangwang_heretic_huibao: "a fallen Shaolin monk with wild eyes in torn dark robes",
  sect_gumu_mystery_woman: "a cold beautiful woman in pure white silk with a long white ribbon",
  sect_xuedao_blade_xuelang: "a Blood Blade lama with red eyes in maroon robes holding a blood-red sabre",
  city_lingxiao_guard_feng: "a stern woman gate guard in a fur-lined coat with a spear",
  city_lingxiao_coal_hu: "a burly coal seller with a soot-black face and a basket of charcoal",
  village_noname_whip_qiao: "an old woman goatherd with a long leather whip",
};

export interface ActorJob { id: string; npc: string; name: string; prompt: string; gender: "male" | "female"; age: "child" | "adult" | "elder"; sect?: string }

const SECTS = Object.keys(SECT_DRESS);

export function npcPrompt(npc: NpcDef): ActorJob {
  const tags = npc.tags ?? [];
  const tagText = tags.join(" ");
  const body = npcCharacterId(npc.id);
  const text = `${npc.name} ${npc.description ?? ""}`;
  const female = /^f\d/.test(body) || /\b(nun|swordswoman|lady_warrior|maid|daughter)\b/.test(tagText)
    || /หญิง|สาว|นาง|ยาย|ป้า|แม่ครัว|เนี้ย|ภิกษุณี/.test(text);
  const child = tags.includes("child") || /เด็ก/.test(npc.name);
  const elder = !child && (tags.includes("elder") || body === "elder" || /ชรา|เฒ่า|แก่|ยาย|ลุง|ป้า/.test(text));
  const sect = SECTS.find((s) => tags.includes(s));
  const role = OVERRIDES[npc.id]
    ?? (sect ? SECT_DRESS[sect] : undefined)
    ?? ROLE_DRESS.find(([re]) => re.test(tagText))?.[1]
    ?? "a commoner in plain hemp clothes";
  const rank = tags.includes("sect_master") || tags.includes("chief") ? ", a dignified sect leader in an ornate version of the robe"
    : tags.includes("vice_master") || tags.includes("vice_abbot") || tags.includes("vice_chief") ? ", a senior master" : "";
  const who = child ? (female ? "little girl" : "little boy") : elder ? (female ? "old woman with grey hair" : "old man with a white beard") : (female ? "woman" : "man");
  const region = npc.locationIds.some((l) => /lingxiao|bingcan/.test(l)) ? ", wearing a warm fur-lined coat" : "";
  const prompt = `${who}, ${role}${rank}${region}; ancient China wuxia character, muted colours`;
  return { id: npc.id, npc: npc.id, name: npc.name, prompt, gender: female ? "female" : "male", age: child ? "child" : elder ? "elder" : "adult", sect };
}

/** [key, Thai, English subject, subcategory, template] — 116 monsters. */
export const MONSTERS: [string, string, string, string, string][] = [
  // ─── beasts from the game's foes ───
  ["wild_dog", "หมาป่าเล็ก", "a scrawny wild dog", "beast", "dog"],
  ["wild_chicken", "ไก่ป่า", "a red jungle fowl rooster", "beast", "dog"],
  ["small_snake", "งูเล็ก", "a small green snake coiled", "beast", "dog"],
  ["wild_boar", "หมูป่า", "a bristly wild boar with tusks", "beast", "horse"],
  ["wolf", "หมาป่า", "a grey wolf", "beast", "dog"],
  ["mountain_tiger", "เสือภูเขา", "a big striped mountain tiger", "beast", "lion"],
  ["brown_bear", "หมีสีน้ำตาล", "a brown bear", "beast", "bear"],
  ["giant_viper", "งูเห่ายักษ์", "a giant hooded cobra rearing up", "beast", "dog"],
  ["giant_centipede", "ตะขาบยักษ์", "a giant red centipede", "beast", "dog"],
  ["snow_leopard", "เสือดาวหิมะ", "a white snow leopard with grey rosettes and a long thick tail", "beast", "cat"],
  ["rabbit", "กระต่ายป่า", "a brown wild hare", "beast", "cat"],
  ["pheasant", "ไก่ฟ้า", "a golden pheasant with a long tail", "beast", "dog"],
  ["squirrel", "กระรอก", "a red squirrel with a bushy tail", "beast", "cat"],
  ["leopard", "เสือดาวป่า", "a spotted jungle leopard", "beast", "cat"],
  ["alpha_wolf", "หมาป่าจ่าฝูง", "a huge scarred alpha wolf", "beast", "dog"],
  ["stone_bear", "หมีหิน", "a giant bear with rocky grey hide", "beast", "bear"],
  ["lynx", "เสือเขาเล็ก", "a mountain lynx", "beast", "cat"],
  ["jungle_serpent", "งูยักษ์ป่า", "a giant jungle python", "beast", "dog"],
  ["vampire_bat", "ค้างคาวดูดเลือด", "a giant vampire bat with spread wings", "beast", "mannequin"],
  ["frost_wolf", "หมาป่าหิมะ", "a white frost wolf with icy breath", "beast", "dog"],
  ["blood_boar", "หมูป่าเลือดคลั่ง", "a berserk red-eyed blood boar", "beast", "horse"],
  ["golden_tiger", "เสือทองคำ", "a golden-furred tiger", "beast", "lion"],
  ["jade_python", "งูเหลือมหยก", "a jade-green giant python", "beast", "dog"],
  ["thunder_eagle", "อินทรีสายฟ้า", "a huge eagle crackling with lightning", "beast", "mannequin"],
  ["bear_king", "ราชาหมีพันปี", "an enormous ancient bear king with grey fur", "beast", "bear"],
  ["shadowless_swordsman", "จอมกระบี่ไร้เงา", "a lean swordsman in pale blue robes caught mid-dash, sword drawn, a blur of speed", "human", "mannequin"],
  // ─── more beasts ───
  ["monkey", "ลิง", "a macaque monkey", "beast", "cat"],
  ["white_ape", "วานรเผือก", "a great white ape", "beast", "mannequin"],
  ["deer", "กวาง", "a sika deer", "beast", "horse"],
  ["stag", "กวางเขาใหญ่", "a large stag with antlers", "beast", "horse"],
  ["yak", "จามรี", "a shaggy black yak", "beast", "horse"],
  ["camel", "อูฐ", "a two-humped Bactrian camel", "beast", "horse"],
  ["wild_horse", "ม้าป่า", "a wild steppe horse", "beast", "horse"],
  ["crocodile", "จระเข้", "a crocodile", "beast", "dog"],
  ["golden_toad", "คางคกทอง", "a giant golden toad", "beast", "dog"],
  ["giant_scorpion", "แมงป่องยักษ์", "a giant black scorpion", "beast", "dog"],
  ["giant_spider", "แมงมุมยักษ์", "a giant hairy spider", "beast", "dog"],
  ["red_crane", "นกกระเรียนมงกุฎแดง", "a red-crowned crane", "beast", "mannequin"],
  ["vulture", "แร้ง", "a mountain vulture", "beast", "mannequin"],
  ["golden_eagle", "อินทรีทอง", "a golden eagle", "beast", "mannequin"],
  ["golden_snake", "งูทอง", "a golden snake with glittering scales", "beast", "dog"],
  ["black_bear", "หมีดำ", "an Asian black bear with a white chest mark", "beast", "bear"],
  ["panda", "หมีแพนด้า", "a giant panda", "beast", "bear"],
  ["snow_leopard", "เสือดาวหิมะ", "a snow leopard", "beast", "cat"],
  ["red_fox", "จิ้งจอกแดง", "a red fox", "beast", "dog"],
  ["giant_rat", "หนูยักษ์", "a giant sewer rat", "beast", "dog"],
  ["jade_bee", "ผึ้งหยก", "a giant white jade bee", "beast", "mannequin"],
  ["salamander", "ซาลาแมนเดอร์ยักษ์", "a giant Chinese salamander", "beast", "dog"],
  ["giant_crab", "ปูยักษ์", "a giant shore crab, the animal only, with big claws", "beast", "dog"],
  ["sea_turtle", "เต่ายักษ์", "a giant old sea turtle, the animal only, with a mossy shell", "beast", "dog"],
  ["water_snake", "งูน้ำ", "a striped water snake", "beast", "dog"],
  ["hornet_swarm", "ฝูงแตน", "a swarm of giant hornets", "beast", "mannequin"],
  ["war_horse", "ม้าศึก", "an armoured war horse", "beast", "horse"],
  ["water_buffalo", "ควายป่า", "a wild water buffalo", "beast", "horse"],
  ["mountain_goat", "แพะภูเขา", "a mountain goat with curved horns", "beast", "horse"],
  ["tiger_cub", "ลูกเสือ", "a tiger cub", "beast", "cat"],
  // ─── spirits and demons ───
  ["jiangshi", "ผีกระโดด", "a jiangshi hopping vampire in Qing official robes with a paper talisman on the forehead", "undead", "mannequin"],
  ["jiangshi_lady", "ผีกระโดดหญิง", "a female jiangshi in faded court robes with outstretched arms", "undead", "mannequin"],
  ["white_ghost", "ผีหญิงชุดขาว", "a female ghost in white with long black hair over her face", "spirit", "mannequin"],
  ["hungry_ghost", "เปรต", "an emaciated hungry ghost with a huge belly and thin neck", "spirit", "mannequin"],
  ["skeleton_warrior", "โครงกระดูกนักรบ", "a skeleton warrior in rusted armour with a sabre", "undead", "mannequin"],
  ["zombie_bandit", "ศพโจรคืนชีพ", "a rotting zombie bandit", "undead", "mannequin"],
  ["ox_head", "หัววัว", "Ox-Head, the underworld guard with a bull's head and a trident", "demon", "mannequin"],
  ["horse_face", "หน้าม้า", "Horse-Face, the underworld guard with a horse's head and a halberd", "demon", "mannequin"],
  ["fox_spirit", "ปีศาจจิ้งจอก", "a nine-tailed fox spirit woman", "spirit", "mannequin"],
  ["nine_tail_fox", "จิ้งจอกเก้าหาง", "a white nine-tailed fox", "spirit", "dog"],
  ["tree_demon", "ปีศาจต้นไม้", "a gnarled tree demon with a twisted face", "demon", "mannequin"],
  ["stone_guardian", "ผู้พิทักษ์หิน", "a living stone guardian lion", "construct", "lion"],
  ["fire_demon", "ปีศาจไฟ", "a fire demon made of flames", "demon", "mannequin"],
  ["water_demon", "ผีน้ำ", "a drowned water ghoul dripping with weeds", "demon", "mannequin"],
  ["mountain_imp", "ภูตภูเขา", "a one-legged mountain imp (shanxiao)", "demon", "mannequin"],
  ["bat_demon", "ปีศาจค้างคาว", "a bat-winged demon", "demon", "mannequin"],
  ["spider_demoness", "ปีศาจแมงมุม", "a spider demoness with spider legs from her back", "demon", "mannequin"],
  ["scorpion_demoness", "ปีศาจแมงป่อง", "a scorpion demoness with a stinger tail", "demon", "mannequin"],
  ["white_bone_demon", "ปีศาจกระดูกขาว", "the white bone demon, a skeletal witch in white", "demon", "mannequin"],
  ["bear_demon", "ปีศาจหมีดำ", "a black bear demon in armour", "demon", "mannequin"],
  ["bull_demon_king", "ราชาปีศาจกระทิง", "a bull demon king with huge horns and an iron staff", "boss", "mannequin"],
  ["monkey_demon", "ปีศาจลิง", "a six-eared monkey demon with a staff", "demon", "mannequin"],
  ["flood_dragon", "มังกรน้ำ", "a young flood dragon (jiao) serpent", "beast", "dog"],
  ["qilin", "กิเลน", "a qilin with scales, a single horn and flaming hooves", "spirit", "horse"],
  ["mech_puppet", "หุ่นกลไก", "a Tang clan mechanical wooden puppet warrior", "construct", "mannequin"],
  ["terracotta_warrior", "ทหารดินเผา", "a terracotta warrior come to life", "construct", "mannequin"],
  ["blood_corpse", "ศพโลหิต", "a blood-soaked corpse fiend", "undead", "mannequin"],
  ["shadow_wraith", "เงาวิญญาณ", "a shadow wraith made of black smoke", "spirit", "mannequin"],
  ["snake_spirit", "นางพญางูขาว", "a white snake spirit woman with a serpent tail", "spirit", "mannequin"],
  ["toad_demon", "ปีศาจคางคก", "a bloated poison toad demon", "demon", "dog"],
  // ─── human foe archetypes ───
  ["bandit", "โจรป่า", "a mountain bandit with a broad sabre and a headband", "human", "mannequin"],
  ["bandit_archer", "โจรธนู", "a bandit archer with a short bow", "human", "mannequin"],
  ["bandit_chief", "หัวหน้าโจร", "a burly bandit chief with a big axe", "human", "mannequin"],
  ["pirate", "โจรสลัด", "a coastal pirate with a cutlass and a red sash", "human", "mannequin"],
  ["night_assassin", "นักฆ่ายามราตรี", "a night assassin in black with a mask and daggers", "human", "mannequin"],
  ["female_assassin", "นักฆ่าหญิง", "a female assassin in dark red with throwing knives", "human", "mannequin"],
  ["poisoner", "นักปรุงพิษ", "a hunched poisoner with gourds of venom", "human", "mannequin"],
  ["cultist", "สาวกลัทธิ", "a cultist in red and black robes", "human", "mannequin"],
  ["blood_monk", "พระโลหิต", "an evil lama monk with a blood-red sabre", "human", "mannequin"],
  ["imperial_spearman", "ทหารทวน", "an imperial soldier with a spear and lamellar armour", "human", "mannequin"],
  ["crossbowman", "ทหารหน้าไม้", "an imperial crossbowman", "human", "mannequin"],
  ["frontier_raider", "โจรทุ่งหญ้า", "a steppe raider in fur with a curved sword", "human", "mannequin"],
  ["desert_raider", "โจรทะเลทราย", "a desert raider with a face veil and scimitar", "human", "mannequin"],
  ["jinyiwei_agent", "สายลับองครักษ์", "an Embroidered Uniform Guard agent in red-gold with a slim sabre", "human", "mannequin"],
  ["eunuch_assassin", "ขันทีนักฆ่า", "a sinister eunuch assassin with long needles", "human", "mannequin"],
  ["evil_monk", "พระนอกรีต", "an evil monk with a heavy iron staff", "human", "mannequin"],
  ["drunken_brawler", "นักเลงเมา", "a drunken brawler with a wine jug", "human", "mannequin"],
  ["thief", "ขโมย", "a sneaky thief with a sack", "human", "mannequin"],
  ["thug", "นักเลงกระบอง", "a thug with a wooden club", "human", "mannequin"],
  ["mercenary", "ทหารรับจ้าง", "a mercenary swordsman in worn armour", "human", "mannequin"],
  ["executioner", "เพชฌฆาต", "a hulking executioner with a huge axe and red hood", "human", "mannequin"],
  ["guard_captain", "หัวหน้าองครักษ์", "a guard captain with a halberd", "human", "mannequin"],
  ["shenlong_disciple", "สาวกเทพมังกร", "a Divine Dragon cult disciple with a dragon tattoo and spear", "human", "mannequin"],
  ["xingxiu_poisoner", "ศิษย์ดาวดึงส์", "a Xingxiu poison disciple in purple with needles", "human", "mannequin"],
  ["miao_warrior", "นักรบเมี่ยว", "a Miao warrior with a silver headdress and machete", "human", "mannequin"],
  ["sword_rogue", "จอมกระบี่นอกรีต", "a rogue swordswoman in black and red", "human", "mannequin"],
  ["giant_brute", "ยักษ์ร่างใหญ่", "a giant brute with iron knuckles", "human", "mannequin"],
  ["ninja_shadow", "เงานักฆ่าเกาะ", "an island shadow warrior in dark grey with a short blade", "human", "mannequin"],
  ["prison_guard", "ผู้คุมคุก", "a prison guard with a whip and keys", "human", "mannequin"],
  ["blade_bodyguard", "ผู้คุ้มกันดาบ", "an escort bodyguard with a big dao", "human", "mannequin"],
];
